{
  "SchemaVersion": 2,
  "ArtifactName": "jsons/docker_scout/sboms/odoo_sbom.json",
  "ArtifactType": "spdx",
  "Metadata": {
    "OS": {
      "Family": "none",
      "Name": ""
    },
    "ImageConfig": {
      "architecture": "",
      "created": "0001-01-01T00:00:00Z",
      "os": "",
      "rootfs": {
        "type": "",
        "diff_ids": null
      },
      "config": {}
    }
  },
  "Results": [
    {
      "Target": "Node.js",
      "Class": "lang-pkgs",
      "Type": "node-pkg",
      "Vulnerabilities": [
        {
          "VulnerabilityID": "CVE-2022-33987",
          "PkgName": "got",
          "InstalledVersion": "11.8.3",
          "FixedVersion": "12.1.0, 11.8.5",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-33987",
          "PkgRef": "pkg:npm/got@11.8.3",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory npm",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Anpm"
          },
          "Title": "nodejs-got: missing verification of requested URLs allows redirects to UNIX sockets",
          "Description": "The got package before 12.1.0 (also fixed in 11.8.5) for Node.js allows a redirect to a UNIX socket.",
          "Severity": "MEDIUM",
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 5.3
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
              "V2Score": 5,
              "V3Score": 5.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 5.3
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2022:6448",
            "https://access.redhat.com/security/cve/CVE-2022-33987",
            "https://bugzilla.redhat.com/2102001",
            "https://bugzilla.redhat.com/2105422",
            "https://bugzilla.redhat.com/2105426",
            "https://bugzilla.redhat.com/2105428",
            "https://bugzilla.redhat.com/2105430",
            "https://errata.almalinux.org/8/ALSA-2022-6448.html",
            "https://github.com/sindresorhus/got",
            "https://github.com/sindresorhus/got/commit/861ccd9ac2237df762a9e2beed7edd88c60782dc",
            "https://github.com/sindresorhus/got/compare/v12.0.3...v12.1.0",
            "https://github.com/sindresorhus/got/pull/2047",
            "https://github.com/sindresorhus/got/releases/tag/v11.8.5",
            "https://github.com/sindresorhus/got/releases/tag/v12.1.0",
            "https://linux.oracle.com/cve/CVE-2022-33987.html",
            "https://linux.oracle.com/errata/ELSA-2022-6595.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-33987",
            "https://www.cve.org/CVERecord?id=CVE-2022-33987"
          ],
          "PublishedDate": "2022-06-18T21:15:07.933Z",
          "LastModifiedDate": "2022-06-28T16:15:31.27Z"
        },
        {
          "VulnerabilityID": "CVE-2022-25881",
          "PkgName": "http-cache-semantics",
          "InstalledVersion": "4.1.0",
          "FixedVersion": "4.1.1",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-25881",
          "PkgRef": "pkg:npm/http-cache-semantics@4.1.0",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory npm",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Anpm"
          },
          "Title": "http-cache-semantics: Regular Expression Denial of Service (ReDoS) vulnerability",
          "Description": "This affects versions of the package http-cache-semantics before 4.1.1. The issue can be exploited via malicious request header values sent to a server, when that server reads the cache policy from the request using this library.\r\r",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-1333"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:1743",
            "https://access.redhat.com/security/cve/CVE-2022-25881",
            "https://bugzilla.redhat.com/2134609",
            "https://bugzilla.redhat.com/2156324",
            "https://bugzilla.redhat.com/2165824",
            "https://bugzilla.redhat.com/2168631",
            "https://bugzilla.redhat.com/2170644",
            "https://bugzilla.redhat.com/2171935",
            "https://bugzilla.redhat.com/2172217",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2165824",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2168631",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2171935",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2172190",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2172204",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2172217",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2178076",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-25881",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-4904",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-23918",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-23920",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-23936",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-24807",
            "https://errata.almalinux.org/8/ALSA-2023-1743.html",
            "https://errata.rockylinux.org/RLSA-2023:2655",
            "https://github.com/kornelski/http-cache-semantics",
            "https://github.com/kornelski/http-cache-semantics/blob/master/index.js%23L83",
            "https://github.com/kornelski/http-cache-semantics/commit/560b2d8ef452bbba20ffed69dc155d63ac757b74",
            "https://linux.oracle.com/cve/CVE-2022-25881.html",
            "https://linux.oracle.com/errata/ELSA-2023-2655.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-25881",
            "https://security.netapp.com/advisory/ntap-20230622-0008",
            "https://security.netapp.com/advisory/ntap-20230622-0008/",
            "https://security.snyk.io/vuln/SNYK-JAVA-ORGWEBJARSNPM-3253332",
            "https://security.snyk.io/vuln/SNYK-JS-HTTPCACHESEMANTICS-3248783",
            "https://www.cve.org/CVERecord?id=CVE-2022-25881"
          ],
          "PublishedDate": "2023-01-31T05:15:11.81Z",
          "LastModifiedDate": "2023-11-07T03:44:51.8Z"
        },
        {
          "VulnerabilityID": "CVE-2023-42282",
          "PkgName": "ip",
          "InstalledVersion": "1.1.5",
          "FixedVersion": "2.0.1, 1.1.9",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-42282",
          "PkgRef": "pkg:npm/ip@1.1.5",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory npm",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Anpm"
          },
          "Title": "nodejs-ip: arbitrary code execution via the isPublic() function",
          "Description": "The ip package before 1.1.9 for Node.js might allow SSRF because some IP addresses (such as 0x7f.1) are improperly categorized as globally routable via isPublic.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-918"
          ],
          "CVSS": {
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2023-42282",
            "https://cosmosofcyberspace.github.io/npm_ip_cve/npm_ip_cve.html",
            "https://github.com/JoshGlazebrook/socks/issues/93#issue-2128357447",
            "https://github.com/github/advisory-database/pull/3504#issuecomment-1937179999",
            "https://github.com/indutny/node-ip",
            "https://github.com/indutny/node-ip/commit/32f468f1245574785ec080705737a579be1223aa",
            "https://github.com/indutny/node-ip/commit/6a3ada9b471b09d5f0f5be264911ab564bf67894",
            "https://github.com/indutny/node-ip/pull/138",
            "https://huntr.com/bounties/bfc3b23f-ddc0-4ee7-afab-223b07115ed3/",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-42282",
            "https://security.netapp.com/advisory/ntap-20240315-0008/",
            "https://ubuntu.com/security/notices/USN-6643-1",
            "https://www.cve.org/CVERecord?id=CVE-2023-42282"
          ],
          "PublishedDate": "2024-02-08T17:15:10.84Z",
          "LastModifiedDate": "2024-03-15T19:25:07.84Z"
        },
        {
          "VulnerabilityID": "CVE-2022-29244",
          "PkgName": "npm",
          "InstalledVersion": "8.5.1",
          "FixedVersion": "8.11.0",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-29244",
          "PkgRef": "pkg:npm/npm@8.5.1",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory npm",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Anpm"
          },
          "Title": "nodejs: npm pack ignores root-level .gitignore and .npmignore file exclusion directives when run in a workspace",
          "Description": "npm pack ignores root-level .gitignore and .npmignore file exclusion directives when run in a workspace or with a workspace flag (ie. `--workspaces`, `--workspace=\u003cname\u003e`). Anyone who has run `npm pack` or `npm publish` inside a workspace, as of v7.9.0 and v7.13.0 respectively, may be affected and have published files into the npm registry they did not intend to include. Users should upgrade to the latest, patched version of npm v8.11.0, run: npm i -g npm@latest . Node.js versions v16.15.1, v17.19.1, and v18.3.0 include the patched v8.11.0 version of npm.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-200"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2022:6595",
            "https://access.redhat.com/security/cve/CVE-2022-29244",
            "https://bugzilla.redhat.com/1907444",
            "https://bugzilla.redhat.com/1945459",
            "https://bugzilla.redhat.com/1964461",
            "https://bugzilla.redhat.com/2007557",
            "https://bugzilla.redhat.com/2098556",
            "https://bugzilla.redhat.com/2102001",
            "https://bugzilla.redhat.com/2105422",
            "https://bugzilla.redhat.com/2105426",
            "https://bugzilla.redhat.com/2105428",
            "https://bugzilla.redhat.com/2105430",
            "https://errata.almalinux.org/9/ALSA-2022-6595.html",
            "https://github.com/nodejs/node/pull/43210",
            "https://github.com/nodejs/node/releases/tag/v16.15.1",
            "https://github.com/nodejs/node/releases/tag/v17.9.1",
            "https://github.com/nodejs/node/releases/tag/v18.3.0",
            "https://github.com/npm/cli",
            "https://github.com/npm/cli/releases/tag/v8.11.0",
            "https://github.com/npm/cli/security/advisories/GHSA-hj9c-8jmm-8c52",
            "https://github.com/npm/cli/tree/latest/workspaces/libnpmpack",
            "https://github.com/npm/cli/tree/latest/workspaces/libnpmpublish",
            "https://github.com/npm/npm-packlist",
            "https://linux.oracle.com/cve/CVE-2022-29244.html",
            "https://linux.oracle.com/errata/ELSA-2022-6595.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-29244",
            "https://security.netapp.com/advisory/ntap-20220722-0007",
            "https://security.netapp.com/advisory/ntap-20220722-0007/",
            "https://www.cve.org/CVERecord?id=CVE-2022-29244"
          ],
          "PublishedDate": "2022-06-13T14:15:09.027Z",
          "LastModifiedDate": "2022-10-27T16:25:40.193Z"
        },
        {
          "VulnerabilityID": "CVE-2022-25883",
          "PkgName": "semver",
          "InstalledVersion": "7.3.5",
          "FixedVersion": "7.5.2, 6.3.1, 5.7.2",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-25883",
          "PkgRef": "pkg:npm/semver@7.3.5",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory npm",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Anpm"
          },
          "Title": "nodejs-semver: Regular expression denial of service",
          "Description": "Versions of the package semver before 7.5.2 are vulnerable to Regular Expression Denial of Service (ReDoS) via the function new Range, when untrusted user data is provided as a range.\r\r\r",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-1333"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
              "V3Score": 5.3
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:5362",
            "https://access.redhat.com/security/cve/CVE-2022-25883",
            "https://bugzilla.redhat.com/2216475",
            "https://bugzilla.redhat.com/2230948",
            "https://bugzilla.redhat.com/2230955",
            "https://bugzilla.redhat.com/2230956",
            "https://errata.almalinux.org/8/ALSA-2023-5362.html",
            "https://github.com/advisories/GHSA-c2qf-rxjj-qqgw",
            "https://github.com/npm/node-semver",
            "https://github.com/npm/node-semver/blob/main/classes/range.js#L97-L104",
            "https://github.com/npm/node-semver/blob/main/classes/range.js%23L97-L104",
            "https://github.com/npm/node-semver/blob/main/internal/re.js#L138",
            "https://github.com/npm/node-semver/blob/main/internal/re.js#L160",
            "https://github.com/npm/node-semver/blob/main/internal/re.js%23L138",
            "https://github.com/npm/node-semver/blob/main/internal/re.js%23L160",
            "https://github.com/npm/node-semver/commit/2f8fd41487acf380194579ecb6f8b1bbfe116be0",
            "https://github.com/npm/node-semver/commit/717534ee353682f3bcf33e60a8af4292626d4441",
            "https://github.com/npm/node-semver/commit/928e56d21150da0413a3333a3148b20e741a920c",
            "https://github.com/npm/node-semver/pull/564",
            "https://github.com/npm/node-semver/pull/585",
            "https://github.com/npm/node-semver/pull/593",
            "https://linux.oracle.com/cve/CVE-2022-25883.html",
            "https://linux.oracle.com/errata/ELSA-2023-5363.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-25883",
            "https://security.snyk.io/vuln/SNYK-JS-SEMVER-3247795",
            "https://www.cve.org/CVERecord?id=CVE-2022-25883"
          ],
          "PublishedDate": "2023-06-21T05:15:09.06Z",
          "LastModifiedDate": "2023-11-07T03:44:51.993Z"
        },
        {
          "VulnerabilityID": "CVE-2024-28863",
          "PkgName": "tar",
          "InstalledVersion": "6.1.11",
          "FixedVersion": "6.2.1",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-28863",
          "PkgRef": "pkg:npm/tar@6.1.11",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory npm",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Anpm"
          },
          "Title": "node-tar is a Tar for Node.js. node-tar prior to version 6.2.1 has no  ...",
          "Description": "node-tar is a Tar for Node.js. node-tar prior to version 6.2.1 has no limit on the number of sub-folders created in the folder creation process. An attacker who generates a large number of sub-folders can consume memory on the system running node-tar and even crash the Node.js client within few seconds of running it using a path with too many sub-folders inside. Version 6.2.1 fixes this issue by preventing extraction in excessively deep sub-folders.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-400",
            "CWE-770"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
              "V3Score": 6.5
            }
          },
          "References": [
            "https://github.com/isaacs/node-tar",
            "https://github.com/isaacs/node-tar/commit/fe8cd57da5686f8695415414bda49206a545f7f7",
            "https://github.com/isaacs/node-tar/commit/fe8cd57da5686f8695415414bda49206a545f7f7 (v6.2.1)",
            "https://github.com/isaacs/node-tar/security/advisories/GHSA-f5x3-32g6-xq36",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-28863",
            "https://www.cve.org/CVERecord?id=CVE-2024-28863"
          ],
          "PublishedDate": "2024-03-21T23:15:10.91Z",
          "LastModifiedDate": "2024-03-22T12:45:36.13Z"
        }
      ]
    },
    {
      "Target": "Python",
      "Class": "lang-pkgs",
      "Type": "python-pkg",
      "Vulnerabilities": [
        {
          "VulnerabilityID": "CVE-2021-42771",
          "PkgName": "babel",
          "InstalledVersion": "2.8.0",
          "FixedVersion": "2.9.1",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-42771",
          "PkgRef": "pkg:pypi/babel@2.8.0",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-babel: Relative path traversal allows attacker to load arbitrary locale files and execute arbitrary code",
          "Description": "Babel.Locale in Babel before 2.9.1 allows attackers to load arbitrary locale .dat files (containing serialized Python objects) via directory traversal, leading to code execution.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 7.8
            },
            "nvd": {
              "V2Vector": "AV:L/AC:L/Au:N/C:C/I:C/A:C",
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
              "V2Score": 7.2,
              "V3Score": 7.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 7.8
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2021-42771",
            "https://bugzilla.redhat.com/show_bug.cgi?id=1955615",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-20095",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-42771",
            "https://errata.almalinux.org/8/ALSA-2021-4201.html",
            "https://errata.rockylinux.org/RLSA-2021:4201",
            "https://github.com/python-babel/babel",
            "https://github.com/python-babel/babel/pull/782",
            "https://linux.oracle.com/cve/CVE-2021-42771.html",
            "https://linux.oracle.com/errata/ELSA-2021-4201.html",
            "https://lists.debian.org/debian-lts-announce/2021/10/msg00018.html",
            "https://lists.debian.org/debian-lts/2021/10/msg00040.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-42771",
            "https://www.cve.org/CVERecord?id=CVE-2021-42771",
            "https://www.debian.org/security/2021/dsa-5018",
            "https://www.tenable.com/security/research/tra-2021-14"
          ],
          "PublishedDate": "2021-10-20T21:15:07.93Z",
          "LastModifiedDate": "2021-12-14T21:22:17.273Z"
        },
        {
          "VulnerabilityID": "CVE-2023-37920",
          "PkgName": "certifi",
          "InstalledVersion": "2020.6.20",
          "FixedVersion": "2023.7.22",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-37920",
          "PkgRef": "pkg:pypi/certifi@2020.6.20",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-certifi: Removal of e-Tugra root certificate",
          "Description": "Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi prior to version 2023.07.22 recognizes \"e-Tugra\" root certificates. e-Tugra's root certificates were subject to an investigation prompted by reporting of security issues in their systems. Certifi 2023.07.22 removes root certificates from \"e-Tugra\" from the root store.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-345"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
              "V3Score": 9.1
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2024:0133",
            "https://access.redhat.com/security/cve/CVE-2023-37920",
            "https://bugzilla.redhat.com/2226586",
            "https://bugzilla.redhat.com/2242493",
            "https://errata.almalinux.org/8/ALSA-2024-0133.html",
            "https://github.com/certifi/python-certifi",
            "https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909",
            "https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7",
            "https://github.com/pypa/advisory-database/tree/main/vulns/certifi/PYSEC-2023-135.yaml",
            "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A",
            "https://linux.oracle.com/cve/CVE-2023-37920.html",
            "https://linux.oracle.com/errata/ELSA-2024-0133.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-37920",
            "https://www.cve.org/CVERecord?id=CVE-2023-37920"
          ],
          "PublishedDate": "2023-07-25T21:15:10.827Z",
          "LastModifiedDate": "2023-08-12T06:16:31.077Z"
        },
        {
          "VulnerabilityID": "CVE-2022-23491",
          "PkgName": "certifi",
          "InstalledVersion": "2020.6.20",
          "FixedVersion": "2022.12.07",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-23491",
          "PkgRef": "pkg:pypi/certifi@2020.6.20",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-certifi: untrusted root certificates",
          "Description": "Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi 2022.12.07 removes root certificates from \"TrustCor\" from the root store. These are in the process of being removed from Mozilla's trust store. TrustCor's root certificates are being removed pursuant to an investigation prompted by media reporting that TrustCor's ownership also operated a business that produced spyware. Conclusions of Mozilla's investigation can be found in the linked google group discussion.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-345"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:N/I:H/A:N",
              "V3Score": 6.8
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2022-23491",
            "https://github.com/certifi/python-certifi",
            "https://github.com/certifi/python-certifi/commit/9e9e840925d7b8e76c76fdac1fab7e6e88c1c3b8",
            "https://github.com/certifi/python-certifi/security/advisories/GHSA-43fp-rhv2-5gv8",
            "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-23491",
            "https://ubuntu.com/security/notices/USN-5761-1",
            "https://ubuntu.com/security/notices/USN-5761-2",
            "https://www.cve.org/CVERecord?id=CVE-2022-23491"
          ],
          "PublishedDate": "2022-12-07T22:15:09.87Z",
          "LastModifiedDate": "2023-03-24T18:12:24.36Z"
        },
        {
          "VulnerabilityID": "CVE-2023-0286",
          "PkgName": "cryptography",
          "InstalledVersion": "3.4.8",
          "FixedVersion": "39.0.1",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-0286",
          "PkgRef": "pkg:pypi/cryptography@3.4.8",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "openssl: X.400 address type confusion in X.509 GeneralName",
          "Description": "There is a type confusion vulnerability relating to X.400 address processing\ninside an X.509 GeneralName. X.400 addresses were parsed as an ASN1_STRING but\nthe public structure definition for GENERAL_NAME incorrectly specified the type\nof the x400Address field as ASN1_TYPE. This field is subsequently interpreted by\nthe OpenSSL function GENERAL_NAME_cmp as an ASN1_TYPE rather than an\nASN1_STRING.\n\nWhen CRL checking is enabled (i.e. the application sets the\nX509_V_FLAG_CRL_CHECK flag), this vulnerability may allow an attacker to pass\narbitrary pointers to a memcmp call, enabling them to read memory contents or\nenact a denial of service. In most cases, the attack requires the attacker to\nprovide both the certificate chain and CRL, neither of which need to have a\nvalid signature. If the attacker only controls one of these inputs, the other\ninput must already contain an X.400 address as a CRL distribution point, which\nis uncommon. As such, this vulnerability is most likely to only affect\napplications which have implemented their own functionality for retrieving CRLs\nover a network.\n\n",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-843"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H",
              "V3Score": 7.4
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H",
              "V3Score": 7.4
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H",
              "V3Score": 7.4
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:2932",
            "https://access.redhat.com/security/cve/CVE-2023-0286",
            "https://access.redhat.com/security/cve/cve-2023-0286",
            "https://bugzilla.redhat.com/2164440",
            "https://bugzilla.redhat.com/2164487",
            "https://bugzilla.redhat.com/2164492",
            "https://bugzilla.redhat.com/2164494",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2144000",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2144003",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2144006",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2144008",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2144010",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2144012",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2144015",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2144017",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2144019",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2145170",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2158412",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2164440",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2164487",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2164488",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2164492",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2164494",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2164497",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2164499",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2164500",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-4203",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-4304",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-4450",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-0215",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-0216",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-0217",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-0286",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-0401",
            "https://errata.almalinux.org/8/ALSA-2023-2932.html",
            "https://errata.rockylinux.org/RLSA-2023:0946",
            "https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.6.2-relnotes.txt",
            "https://ftp.openbsd.org/pub/OpenBSD/patches/7.2/common/018_x509.patch.sig",
            "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2c6c9d439b484e1ba9830d8454a34fa4f80fdfe9",
            "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2f7530077e0ef79d98718138716bc51ca0cad658",
            "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=fd2af07dc083a350c959147097003a14a5e8ac4d",
            "https://github.com/pyca/cryptography",
            "https://github.com/pyca/cryptography/security/advisories/GHSA-x4qr-2fvf-3mr5",
            "https://linux.oracle.com/cve/CVE-2023-0286.html",
            "https://linux.oracle.com/errata/ELSA-2023-32791.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-0286",
            "https://rustsec.org/advisories/RUSTSEC-2023-0006.html",
            "https://security.gentoo.org/glsa/202402-08",
            "https://ubuntu.com/security/notices/USN-5844-1",
            "https://ubuntu.com/security/notices/USN-5845-1",
            "https://ubuntu.com/security/notices/USN-5845-2",
            "https://ubuntu.com/security/notices/USN-6564-1",
            "https://www.cve.org/CVERecord?id=CVE-2023-0286",
            "https://www.openssl.org/news/secadv/20230207.txt"
          ],
          "PublishedDate": "2023-02-08T20:15:24.267Z",
          "LastModifiedDate": "2024-02-04T09:15:09.113Z"
        },
        {
          "VulnerabilityID": "CVE-2023-50782",
          "PkgName": "cryptography",
          "InstalledVersion": "3.4.8",
          "FixedVersion": "42.0.0",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-50782",
          "PkgRef": "pkg:pypi/cryptography@3.4.8",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-cryptography: Bleichenbacher timing oracle attack against RSA decryption - incomplete fix for CVE-2020-25659",
          "Description": "A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-203",
            "CWE-208"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2023-50782",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2254432",
            "https://github.com/openssl/openssl/pull/13817",
            "https://github.com/pyca/cryptography",
            "https://github.com/pyca/cryptography/issues/9785",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-50782",
            "https://people.redhat.com/~hkario/marvin/",
            "https://ubuntu.com/security/notices/USN-6663-1",
            "https://ubuntu.com/security/notices/USN-6673-1",
            "https://ubuntu.com/security/notices/USN-6673-2",
            "https://www.cve.org/CVERecord?id=CVE-2023-50782"
          ],
          "PublishedDate": "2024-02-05T21:15:11.183Z",
          "LastModifiedDate": "2024-02-26T16:27:48.08Z"
        },
        {
          "VulnerabilityID": "CVE-2023-23931",
          "PkgName": "cryptography",
          "InstalledVersion": "3.4.8",
          "FixedVersion": "39.0.1",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-23931",
          "PkgRef": "pkg:pypi/cryptography@3.4.8",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-cryptography: memory corruption via immutable objects",
          "Description": "cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. In affected versions `Cipher.update_into` would accept Python objects which implement the buffer protocol, but provide only immutable buffers. This would allow immutable objects (such as `bytes`) to be mutated, thus violating fundamental rules of Python and resulting in corrupted output. This now correctly raises an exception. This issue has been present since `update_into` was originally introduced in cryptography 1.8.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-754"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L",
              "V3Score": 6.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L",
              "V3Score": 6.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L",
              "V3Score": 6.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:7096",
            "https://access.redhat.com/security/cve/CVE-2023-23931",
            "https://bugzilla.redhat.com/2171817",
            "https://errata.almalinux.org/8/ALSA-2023-7096.html",
            "https://github.com/pyca/cryptography",
            "https://github.com/pyca/cryptography/commit/d6951dca25de45abd52da51b608055371fbcde4e",
            "https://github.com/pyca/cryptography/pull/8230/commits/94a50a9731f35405f0357fa5f3b177d46a726ab3",
            "https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r",
            "https://linux.oracle.com/cve/CVE-2023-23931.html",
            "https://linux.oracle.com/errata/ELSA-2023-7096.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-23931",
            "https://ubuntu.com/security/notices/USN-6539-1",
            "https://www.cve.org/CVERecord?id=CVE-2023-23931"
          ],
          "PublishedDate": "2023-02-07T21:15:09.85Z",
          "LastModifiedDate": "2023-02-16T16:57:18.89Z"
        },
        {
          "VulnerabilityID": "CVE-2023-49083",
          "PkgName": "cryptography",
          "InstalledVersion": "3.4.8",
          "FixedVersion": "41.0.6",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-49083",
          "PkgRef": "pkg:pypi/cryptography@3.4.8",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-cryptography: NULL-dereference when loading PKCS7 certificates",
          "Description": "cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Calling `load_pem_pkcs7_certificates` or `load_der_pkcs7_certificates` could lead to a NULL-pointer dereference and segfault. Exploitation of this vulnerability poses a serious risk of Denial of Service (DoS) for any application attempting to deserialize a PKCS7 blob/certificate. The consequences extend to potential disruptions in system availability and stability. This vulnerability has been patched in version 41.0.6.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-476"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "http://www.openwall.com/lists/oss-security/2023/11/29/2",
            "https://access.redhat.com/security/cve/CVE-2023-49083",
            "https://github.com/pyca/cryptography",
            "https://github.com/pyca/cryptography/commit/f09c261ca10a31fe41b1262306db7f8f1da0e48a",
            "https://github.com/pyca/cryptography/pull/9926",
            "https://github.com/pyca/cryptography/security/advisories/GHSA-jfhm-5ghh-2f97",
            "https://github.com/pypa/advisory-database/tree/main/vulns/cryptography/PYSEC-2023-254.yaml",
            "https://linux.oracle.com/cve/CVE-2023-49083.html",
            "https://linux.oracle.com/errata/ELSA-2024-19480.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QMNTYMUGFJSDBYBU22FUYBHFRZODRKXV",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QMNTYMUGFJSDBYBU22FUYBHFRZODRKXV/",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-49083",
            "https://ubuntu.com/security/notices/USN-6539-1",
            "https://www.cve.org/CVERecord?id=CVE-2023-49083"
          ],
          "PublishedDate": "2023-11-29T19:15:07.967Z",
          "LastModifiedDate": "2024-02-17T02:15:45.35Z"
        },
        {
          "VulnerabilityID": "CVE-2024-0727",
          "PkgName": "cryptography",
          "InstalledVersion": "3.4.8",
          "FixedVersion": "42.0.2",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-0727",
          "PkgRef": "pkg:pypi/cryptography@3.4.8",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "openssl: denial of service via null dereference",
          "Description": "Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.",
          "Severity": "MEDIUM",
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
              "V3Score": 5.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
              "V3Score": 5.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
              "V3Score": 5.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-0727",
            "https://github.com/alexcrichton/openssl-src-rs/commit/add20f73b6b42be7451af2e1044d4e0e778992b2",
            "https://github.com/github/advisory-database/pull/3472",
            "https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2",
            "https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a",
            "https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c",
            "https://github.com/openssl/openssl/pull/23362",
            "https://github.com/pyca/cryptography/commit/3519591d255d4506fbcd0d04037d45271903c64d",
            "https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8",
            "https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-0727",
            "https://security.netapp.com/advisory/ntap-20240208-0006",
            "https://security.netapp.com/advisory/ntap-20240208-0006/",
            "https://ubuntu.com/security/notices/USN-6622-1",
            "https://ubuntu.com/security/notices/USN-6632-1",
            "https://ubuntu.com/security/notices/USN-6709-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-0727",
            "https://www.openssl.org/news/secadv/20240125.txt"
          ],
          "PublishedDate": "2024-01-26T09:15:07.637Z",
          "LastModifiedDate": "2024-02-08T10:15:13.91Z"
        },
        {
          "VulnerabilityID": "GHSA-5cpq-8wj7-hf2v",
          "PkgName": "cryptography",
          "InstalledVersion": "3.4.8",
          "FixedVersion": "41.0.0",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://github.com/advisories/GHSA-5cpq-8wj7-hf2v",
          "PkgRef": "pkg:pypi/cryptography@3.4.8",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "Vulnerable OpenSSL included in cryptography wheels",
          "Description": "pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 0.5-40.0.2 are vulnerable to a security issue. More details about the vulnerability itself can be found in https://www.openssl.org/news/secadv/20230530.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.",
          "Severity": "LOW",
          "References": [
            "https://cryptography.io/en/latest/changelog/#v41-0-0",
            "https://github.com/pyca/cryptography",
            "https://github.com/pyca/cryptography/commit/8708245ccdeaff21d65eea68a4f8d2a7c5949a22",
            "https://github.com/pyca/cryptography/security/advisories/GHSA-5cpq-8wj7-hf2v"
          ]
        },
        {
          "VulnerabilityID": "GHSA-jm77-qphf-c4w8",
          "PkgName": "cryptography",
          "InstalledVersion": "3.4.8",
          "FixedVersion": "41.0.3",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://github.com/advisories/GHSA-jm77-qphf-c4w8",
          "PkgRef": "pkg:pypi/cryptography@3.4.8",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "pyca/cryptography's wheels include vulnerable OpenSSL",
          "Description": "pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 0.8-41.0.2 are vulnerable to several security issues. More details about the vulnerabilities themselves can be found in https://www.openssl.org/news/secadv/20230731.txt, https://www.openssl.org/news/secadv/20230719.txt, and https://www.openssl.org/news/secadv/20230714.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.",
          "Severity": "LOW",
          "References": [
            "https://github.com/pyca/cryptography",
            "https://github.com/pyca/cryptography/commit/b22271cf3c3dd8dc8978f8f4b00b5c7060b6538d",
            "https://github.com/pyca/cryptography/commit/bfa4d95f0f356f2d535efd5c775e0fb3efe90ef2",
            "https://github.com/pyca/cryptography/security/advisories/GHSA-jm77-qphf-c4w8",
            "https://www.openssl.org/news/secadv/20230714.txt",
            "https://www.openssl.org/news/secadv/20230719.txt",
            "https://www.openssl.org/news/secadv/20230731.txt"
          ]
        },
        {
          "VulnerabilityID": "GHSA-v8gr-m533-ghj9",
          "PkgName": "cryptography",
          "InstalledVersion": "3.4.8",
          "FixedVersion": "41.0.4",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://github.com/advisories/GHSA-v8gr-m533-ghj9",
          "PkgRef": "pkg:pypi/cryptography@3.4.8",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "Vulnerable OpenSSL included in cryptography wheels",
          "Description": "pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 2.5-41.0.3 are vulnerable to several security issues. More details about the vulnerabilities themselves can be found in https://www.openssl.org/news/secadv/20230908.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.",
          "Severity": "LOW",
          "References": [
            "https://github.com/pyca/cryptography",
            "https://github.com/pyca/cryptography/commit/fc11bce6930e591ce26a2317b31b9ce2b3e25512",
            "https://github.com/pyca/cryptography/security/advisories/GHSA-v8gr-m533-ghj9"
          ]
        },
        {
          "VulnerabilityID": "CVE-2023-41419",
          "PkgName": "gevent",
          "InstalledVersion": "21.8.0",
          "FixedVersion": "23.9.0",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-41419",
          "PkgRef": "pkg:pypi/gevent@21.8.0",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-gevent: privilege escalation via a crafted script to the WSGIServer component",
          "Description": "An issue in Gevent before version 23.9.0 allows a remote attacker to escalate privileges via a crafted script to the WSGIServer component.",
          "Severity": "CRITICAL",
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
              "V3Score": 9.1
            }
          },
          "References": [
            "http://www.gevent.org/changelog.html",
            "https://access.redhat.com/security/cve/CVE-2023-41419",
            "https://github.com/gevent/gevent",
            "https://github.com/gevent/gevent/commit/2f53c851eaf926767fbac62385615efd4886221c",
            "https://github.com/gevent/gevent/issues/1989",
            "https://github.com/pypa/advisory-database/tree/main/vulns/gevent/PYSEC-2023-177.yaml",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-41419",
            "https://www.cve.org/CVERecord?id=CVE-2023-41419"
          ],
          "PublishedDate": "2023-09-25T12:15:11.21Z",
          "LastModifiedDate": "2023-12-08T20:51:32.543Z"
        },
        {
          "VulnerabilityID": "CVE-2024-3651",
          "PkgName": "idna",
          "InstalledVersion": "3.3",
          "FixedVersion": "3.7",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-3651",
          "PkgRef": "pkg:pypi/idna@3.3",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-idna: potential DoS via resource consumption via specially crafted inputs to idna.encode()",
          "Description": "A flaw was found in the python-idna library. A malicious argument was sent to the idna.encode() function can trigger an uncontrolled resource consumption, resulting in a denial of service.",
          "Severity": "MEDIUM",
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 6.2
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 6.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-3651",
            "https://github.com/kjd/idna",
            "https://github.com/kjd/idna/security/advisories/GHSA-jjg7-2v4v-x38h",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-3651",
            "https://www.cve.org/CVERecord?id=CVE-2024-3651"
          ]
        },
        {
          "VulnerabilityID": "CVE-2024-22195",
          "PkgName": "jinja2",
          "InstalledVersion": "3.0.3",
          "FixedVersion": "3.1.3",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-22195",
          "PkgRef": "pkg:pypi/jinja2@3.0.3",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "jinja2: HTML attribute injection when passing user input as keys to xmlattr filter",
          "Description": "Jinja is an extensible templating engine. Special placeholders in the template allow writing code similar to Python syntax. It is possible to inject arbitrary HTML attributes into the rendered HTML template, potentially leading to Cross-Site Scripting (XSS). The Jinja `xmlattr` filter can be abused to inject arbitrary HTML attribute keys and values, bypassing the auto escaping mechanism and potentially leading to XSS. It may also be possible to bypass attribute validation checks if they are blacklist-based.\n",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-79"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N",
              "V3Score": 5.4
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V3Score": 6.1
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N",
              "V3Score": 5.4
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-22195",
            "https://github.com/pallets/jinja",
            "https://github.com/pallets/jinja/commit/716795349a41d4983a9a4771f7d883c96ea17be7",
            "https://github.com/pallets/jinja/releases/tag/3.1.3",
            "https://github.com/pallets/jinja/security/advisories/GHSA-h5c8-rqwp-cp95",
            "https://lists.debian.org/debian-lts-announce/2024/01/msg00010.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5XCWZD464AJJJUBOO7CMPXQ4ROBC6JX2",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5XCWZD464AJJJUBOO7CMPXQ4ROBC6JX2/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DELCVUUYX75I5K4Q5WMJG4MUZJA6VAIP",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DELCVUUYX75I5K4Q5WMJG4MUZJA6VAIP/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O7YWRBX6JQCWC2XXCTZ55C7DPMGICCN3",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O7YWRBX6JQCWC2XXCTZ55C7DPMGICCN3/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-22195",
            "https://ubuntu.com/security/notices/USN-6599-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-22195"
          ],
          "PublishedDate": "2024-01-11T03:15:11.2Z",
          "LastModifiedDate": "2024-01-27T03:15:08.043Z"
        },
        {
          "VulnerabilityID": "CVE-2022-2309",
          "PkgName": "lxml",
          "InstalledVersion": "4.8.0",
          "FixedVersion": "4.9.1",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-2309",
          "PkgRef": "pkg:pypi/lxml@4.8.0",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "lxml: NULL Pointer Dereference in lxml",
          "Description": "NULL Pointer Dereference allows attackers to cause a denial of service (or application crash). This only applies when lxml is used together with libxml2 2.9.10 through 2.9.14. libxml2 2.9.9 and earlier are not affected. It allows triggering crashes through forged input data, given a vulnerable code sequence in the application. The vulnerability is caused by the iterwalk function (also used by the canonicalize function). Such code shouldn't be in wide-spread use, given that parsing + iterwalk would usually be replaced with the more efficient iterparse function. However, an XML converter that serialises to C14N would also be vulnerable, for example, and there are legitimate use cases for this code sequence. If untrusted input is received (also remotely) and processed via iterwalk function, a crash can be triggered.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-476"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
              "V3Score": 5.3
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2022:8226",
            "https://access.redhat.com/security/cve/CVE-2022-2309",
            "https://bugzilla.redhat.com/2107571",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2107571",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-2309",
            "https://errata.almalinux.org/9/ALSA-2022-8226.html",
            "https://errata.rockylinux.org/RLSA-2022:8226",
            "https://github.com/advisories/GHSA-wrxv-2j5q-m38w",
            "https://github.com/lxml/lxml",
            "https://github.com/lxml/lxml/blob/master/CHANGES.txt",
            "https://github.com/lxml/lxml/commit/86368e9cf70a0ad23cccd5ee32de847149af0c6f",
            "https://github.com/lxml/lxml/commit/86368e9cf70a0ad23cccd5ee32de847149af0c6f (lxml-4.9.1)",
            "https://github.com/pypa/advisory-database/tree/main/vulns/lxml/PYSEC-2022-230.yaml",
            "https://gitlab.gnome.org/GNOME/libxml2/-/issues/378",
            "https://huntr.dev/bounties/8264e74f-edda-4c40-9956-49de635105ba",
            "https://huntr.dev/bounties/8264e74f-edda-4c40-9956-49de635105ba/",
            "https://linux.oracle.com/cve/CVE-2022-2309.html",
            "https://linux.oracle.com/errata/ELSA-2022-8226.html",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HGYC6L7ENH5VEGN3YWFBYMGKX6WNS7HZ/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/URHHSIBTPTALXMECRLAC2EVDNAFSR5NO/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HGYC6L7ENH5VEGN3YWFBYMGKX6WNS7HZ",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/URHHSIBTPTALXMECRLAC2EVDNAFSR5NO",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-2309",
            "https://security.gentoo.org/glsa/202208-06",
            "https://security.netapp.com/advisory/ntap-20220915-0006",
            "https://security.netapp.com/advisory/ntap-20220915-0006/",
            "https://ubuntu.com/security/notices/USN-5760-1",
            "https://ubuntu.com/security/notices/USN-6028-2",
            "https://www.cve.org/CVERecord?id=CVE-2022-2309"
          ],
          "PublishedDate": "2022-07-05T10:15:08.763Z",
          "LastModifiedDate": "2023-11-07T03:46:28.713Z"
        },
        {
          "VulnerabilityID": "CVE-2022-45198",
          "PkgName": "pillow",
          "InstalledVersion": "9.0.1",
          "FixedVersion": "9.2.0",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-45198",
          "PkgRef": "pkg:pypi/pillow@9.0.1",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "Pillow before 9.2.0 performs Improper Handling of Highly Compressed GI ...",
          "Description": "Pillow before 9.2.0 performs Improper Handling of Highly Compressed GIF Data (Data Amplification).",
          "Severity": "HIGH",
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://bugs.gentoo.org/855683",
            "https://cwe.mitre.org/data/definitions/409.html",
            "https://github.com/python-pillow/Pillow",
            "https://github.com/python-pillow/Pillow/commit/11918eac0628ec8ac0812670d9838361ead2d6a4",
            "https://github.com/python-pillow/Pillow/pull/6402",
            "https://github.com/python-pillow/Pillow/pull/6402/commits/c9f1b35e981075110a23487a8d4a6cbb59a588ea",
            "https://github.com/python-pillow/Pillow/releases/tag/9.2.0",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-45198",
            "https://security.gentoo.org/glsa/202211-10",
            "https://ubuntu.com/security/notices/USN-5777-1",
            "https://ubuntu.com/security/notices/USN-5777-2",
            "https://www.cve.org/CVERecord?id=CVE-2022-45198"
          ],
          "PublishedDate": "2022-11-14T07:15:10.347Z",
          "LastModifiedDate": "2023-01-10T20:11:59.787Z"
        },
        {
          "VulnerabilityID": "CVE-2023-44271",
          "PkgName": "pillow",
          "InstalledVersion": "9.0.1",
          "FixedVersion": "10.0.0",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-44271",
          "PkgRef": "pkg:pypi/pillow@9.0.1",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-pillow: uncontrolled resource consumption when textlength in an ImageDraw instance operates on a long text argument",
          "Description": "An issue was discovered in Pillow before 10.0.0. It is a Denial of Service that uncontrollably allocates memory to process a given task, potentially causing a service to crash by having it run out of memory. This occurs for truetype in ImageFont when textlength in an ImageDraw instance operates on a long text argument.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-770"
          ],
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2023-44271",
            "https://devhub.checkmarx.com/cve-details/CVE-2023-44271",
            "https://devhub.checkmarx.com/cve-details/CVE-2023-44271/",
            "https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2023-227.yaml",
            "https://github.com/python-pillow/Pillow",
            "https://github.com/python-pillow/Pillow/commit/1fe1bb49c452b0318cad12ea9d97c3bef188e9a7",
            "https://github.com/python-pillow/Pillow/pull/7244",
            "https://linux.oracle.com/cve/CVE-2023-44271.html",
            "https://linux.oracle.com/errata/ELSA-2024-0345.html",
            "https://lists.debian.org/debian-lts-announce/2024/03/msg00021.html",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N2JOEDUJDQLCUII2LQYZYSM7RJL2I3P4",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N2JOEDUJDQLCUII2LQYZYSM7RJL2I3P4/",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-44271",
            "https://ubuntu.com/security/notices/USN-6618-1",
            "https://www.cve.org/CVERecord?id=CVE-2023-44271"
          ],
          "PublishedDate": "2023-11-03T05:15:30.137Z",
          "LastModifiedDate": "2024-03-22T11:15:46.063Z"
        },
        {
          "VulnerabilityID": "CVE-2023-4863",
          "PkgName": "pillow",
          "InstalledVersion": "9.0.1",
          "FixedVersion": "10.0.1",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-4863",
          "PkgRef": "pkg:pypi/pillow@9.0.1",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "libwebp: Heap buffer overflow in WebP Codec",
          "Description": "Heap buffer overflow in libwebp in Google Chrome prior to 116.0.5845.187 and libwebp 1.3.2 allowed a remote attacker to perform an out of bounds memory write via a crafted HTML page. (Chromium security severity: Critical)",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-787"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:H",
              "V3Score": 9.6
            }
          },
          "References": [
            "http://www.openwall.com/lists/oss-security/2023/09/21/4",
            "http://www.openwall.com/lists/oss-security/2023/09/22/1",
            "http://www.openwall.com/lists/oss-security/2023/09/22/3",
            "http://www.openwall.com/lists/oss-security/2023/09/22/4",
            "http://www.openwall.com/lists/oss-security/2023/09/22/5",
            "http://www.openwall.com/lists/oss-security/2023/09/22/6",
            "http://www.openwall.com/lists/oss-security/2023/09/22/7",
            "http://www.openwall.com/lists/oss-security/2023/09/22/8",
            "http://www.openwall.com/lists/oss-security/2023/09/26/1",
            "http://www.openwall.com/lists/oss-security/2023/09/26/7",
            "http://www.openwall.com/lists/oss-security/2023/09/28/1",
            "http://www.openwall.com/lists/oss-security/2023/09/28/2",
            "http://www.openwall.com/lists/oss-security/2023/09/28/4",
            "https://access.redhat.com/errata/RHSA-2023:5309",
            "https://access.redhat.com/security/cve/CVE-2023-4863",
            "https://adamcaudill.com/2023/09/14/whose-cve-is-it-anyway",
            "https://adamcaudill.com/2023/09/14/whose-cve-is-it-anyway/",
            "https://blog.isosceles.com/the-webp-0day",
            "https://blog.isosceles.com/the-webp-0day/",
            "https://bugzilla.redhat.com/2238431",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2238431",
            "https://bugzilla.suse.com/show_bug.cgi?id=1215231",
            "https://chromereleases.googleblog.com/2023/09/stable-channel-update-for-desktop_11.html",
            "https://chromium.googlesource.com/webm/libwebp.git/+/902bc9190331343b2017211debcec8d2ab87e17a",
            "https://crbug.com/1479274",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-4863",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-5129",
            "https://en.bandisoft.com/honeyview/history",
            "https://en.bandisoft.com/honeyview/history/",
            "https://errata.almalinux.org/8/ALSA-2023-5309.html",
            "https://errata.rockylinux.org/RLSA-2023:5214",
            "https://github.com/ImageMagick/ImageMagick/discussions/6664",
            "https://github.com/dlemstra/Magick.NET/releases/tag/13.3.0",
            "https://github.com/electron/electron/pull/39823",
            "https://github.com/electron/electron/pull/39825",
            "https://github.com/electron/electron/pull/39826",
            "https://github.com/electron/electron/pull/39827",
            "https://github.com/electron/electron/pull/39828",
            "https://github.com/jaredforth/webp/commit/9d4c56e63abecc777df71c702503c3eaabd7dcbc",
            "https://github.com/jaredforth/webp/pull/30",
            "https://github.com/python-pillow/Pillow/pull/7395",
            "https://github.com/qnighy/libwebp-sys2-rs/commit/4560c473a76ec8bd8c650f19ddf9d7a44f719f8b",
            "https://github.com/qnighy/libwebp-sys2-rs/pull/21",
            "https://github.com/webmproject/libwebp",
            "https://github.com/webmproject/libwebp/commit/902bc9190331343b2017211debcec8d2ab87e17a",
            "https://github.com/webmproject/libwebp/releases/tag/v1.3.2",
            "https://linux.oracle.com/cve/CVE-2023-4863.html",
            "https://linux.oracle.com/errata/ELSA-2023-5309.html",
            "https://lists.debian.org/debian-lts-announce/2023/09/msg00015.html",
            "https://lists.debian.org/debian-lts-announce/2023/09/msg00016.html",
            "https://lists.debian.org/debian-lts-announce/2023/09/msg00017.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6T655QF7CQ3DYAMPFV7IECQYGDEUIVVT",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6T655QF7CQ3DYAMPFV7IECQYGDEUIVVT/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FYYKLG6CRGEDTNRBSU26EEWAO6D6U645",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FYYKLG6CRGEDTNRBSU26EEWAO6D6U645/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KUQ7CTX3W372X3UY56VVNAHCH6H2F4X3",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KUQ7CTX3W372X3UY56VVNAHCH6H2F4X3/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OZDGWWMJREPAGKWCJKSCM4WYLANSKIFX",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OZDGWWMJREPAGKWCJKSCM4WYLANSKIFX/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PYZV7TMKF4QHZ54SFJX54BDN52VHGGCX",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PYZV7TMKF4QHZ54SFJX54BDN52VHGGCX/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WHOLML7N2G5KCAZXFWC5IDFFHSQS5SDB",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WHOLML7N2G5KCAZXFWC5IDFFHSQS5SDB/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WTRUIS3564P7ZLM2S2IH4Y4KZ327LI4I",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WTRUIS3564P7ZLM2S2IH4Y4KZ327LI4I/",
            "https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-4863",
            "https://news.ycombinator.com/item?id=37478403",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-4863",
            "https://pillow.readthedocs.io/en/stable/releasenotes/10.0.1.html#security",
            "https://rustsec.org/advisories/RUSTSEC-2023-0060.html",
            "https://rustsec.org/advisories/RUSTSEC-2023-0061.html",
            "https://security-tracker.debian.org/tracker/CVE-2023-4863",
            "https://security.gentoo.org/glsa/202309-05",
            "https://security.gentoo.org/glsa/202401-10",
            "https://security.netapp.com/advisory/ntap-20230929-0011",
            "https://security.netapp.com/advisory/ntap-20230929-0011/",
            "https://sethmlarson.dev/security-developer-in-residence-weekly-report-16",
            "https://stackdiary.com/critical-vulnerability-in-webp-codec-cve-2023-4863",
            "https://stackdiary.com/critical-vulnerability-in-webp-codec-cve-2023-4863/",
            "https://ubuntu.com/security/notices/USN-6367-1",
            "https://ubuntu.com/security/notices/USN-6368-1",
            "https://ubuntu.com/security/notices/USN-6369-1",
            "https://ubuntu.com/security/notices/USN-6369-2",
            "https://www.bentley.com/advisories/be-2023-0001",
            "https://www.bentley.com/advisories/be-2023-0001/",
            "https://www.bleepingcomputer.com/news/google/google-fixes-another-chrome-zero-day-bug-exploited-in-attacks",
            "https://www.bleepingcomputer.com/news/google/google-fixes-another-chrome-zero-day-bug-exploited-in-attacks/",
            "https://www.cve.org/CVERecord?id=CVE-2023-4863",
            "https://www.debian.org/security/2023/dsa-5496",
            "https://www.debian.org/security/2023/dsa-5497",
            "https://www.debian.org/security/2023/dsa-5498",
            "https://www.mozilla.org/en-US/security/advisories/mfsa2023-40",
            "https://www.mozilla.org/en-US/security/advisories/mfsa2023-40/"
          ],
          "PublishedDate": "2023-09-12T15:15:24.327Z",
          "LastModifiedDate": "2024-01-07T11:15:13.65Z"
        },
        {
          "VulnerabilityID": "CVE-2023-50447",
          "PkgName": "pillow",
          "InstalledVersion": "9.0.1",
          "FixedVersion": "10.2.0",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-50447",
          "PkgRef": "pkg:pypi/pillow@9.0.1",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "pillow:Arbitrary Code Execution via the environment parameter",
          "Description": "Pillow through 10.1.0 allows PIL.ImageMath.eval Arbitrary Code Execution via the environment parameter, a different vulnerability than CVE-2022-22817 (which was about the expression parameter).",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-94"
          ],
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 8.1
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 8.1
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 8.1
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 8.1
            }
          },
          "References": [
            "http://www.openwall.com/lists/oss-security/2024/01/20/1",
            "https://access.redhat.com/errata/RHSA-2024:0893",
            "https://access.redhat.com/security/cve/CVE-2023-50447",
            "https://bugzilla.redhat.com/2259479",
            "https://devhub.checkmarx.com/cve-details/CVE-2023-50447",
            "https://devhub.checkmarx.com/cve-details/CVE-2023-50447/",
            "https://duartecsantos.github.io/2023-01-02-CVE-2023-50447",
            "https://duartecsantos.github.io/2023-01-02-CVE-2023-50447/",
            "https://duartecsantos.github.io/2024-01-02-CVE-2023-50447",
            "https://duartecsantos.github.io/2024-01-02-CVE-2023-50447/",
            "https://errata.almalinux.org/8/ALSA-2024-0893.html",
            "https://github.com/python-pillow/Pillow",
            "https://github.com/python-pillow/Pillow/commit/45c726fd4daa63236a8f3653530f297dc87b160a",
            "https://github.com/python-pillow/Pillow/releases",
            "https://linux.oracle.com/cve/CVE-2023-50447.html",
            "https://linux.oracle.com/errata/ELSA-2024-0893.html",
            "https://lists.debian.org/debian-lts-announce/2024/01/msg00019.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-50447",
            "https://pillow.readthedocs.io/en/stable/releasenotes/10.2.0.html#imagemath-eval-restricted-environment-keys",
            "https://pillow.readthedocs.io/en/stable/releasenotes/10.2.0.html#security",
            "https://ubuntu.com/security/notices/USN-6618-1",
            "https://www.cve.org/CVERecord?id=CVE-2023-50447"
          ],
          "PublishedDate": "2024-01-19T20:15:11.87Z",
          "LastModifiedDate": "2024-03-27T21:15:48.783Z"
        },
        {
          "VulnerabilityID": "GHSA-56pw-mpj4-fxww",
          "PkgName": "pillow",
          "InstalledVersion": "9.0.1",
          "FixedVersion": "10.0.1",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://github.com/advisories/GHSA-56pw-mpj4-fxww",
          "PkgRef": "pkg:pypi/pillow@9.0.1",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "Bundled libwebp in Pillow vulnerable",
          "Description": "Pillow versions before v10.0.1 bundled libwebp binaries in wheels that are vulnerable to CVE-2023-5129 (previously CVE-2023-4863). Pillow v10.0.1 upgrades the bundled libwebp binary to v1.3.2.",
          "Severity": "HIGH",
          "References": [
            "https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2023-175.yaml",
            "https://github.com/python-pillow/Pillow",
            "https://github.com/python-pillow/Pillow/blob/main/CHANGES.rst#1001-2023-09-15",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-4863",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-5129"
          ]
        },
        {
          "VulnerabilityID": "CVE-2024-28219",
          "PkgName": "pillow",
          "InstalledVersion": "9.0.1",
          "FixedVersion": "10.3.0",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-28219",
          "PkgRef": "pkg:pypi/pillow@9.0.1",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-pillow: buffer overflow in _imagingcms.c",
          "Description": "In _imagingcms.c in Pillow before 10.3.0, a buffer overflow exists because strcpy is used instead of strncpy.",
          "Severity": "MEDIUM",
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 6.7
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:H",
              "V3Score": 7.3
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-28219",
            "https://github.com/python-pillow/Pillow",
            "https://github.com/python-pillow/Pillow/commit/2a93aba5cfcf6e241ab4f9392c13e3b74032c061",
            "https://lists.debian.org/debian-lts-announce/2024/04/msg00008.html",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4XLPUT3VK4GQ6EVY525TT2QNUIXNRU5M",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4XLPUT3VK4GQ6EVY525TT2QNUIXNRU5M/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-28219",
            "https://pillow.readthedocs.io/en/stable/releasenotes/10.3.0.html#security",
            "https://www.cve.org/CVERecord?id=CVE-2024-28219"
          ],
          "PublishedDate": "2024-04-03T03:15:09.71Z",
          "LastModifiedDate": "2024-04-10T22:15:07.193Z"
        },
        {
          "VulnerabilityID": "CVE-2023-5752",
          "PkgName": "pip",
          "InstalledVersion": "22.0.2",
          "FixedVersion": "23.3",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-5752",
          "PkgRef": "pkg:pypi/pip@22.0.2",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "pip: Mercurial configuration injectable in repo revision when installing via pip",
          "Description": "When installing a package from a Mercurial VCS URL  (ie \"pip install \nhg+...\") with pip prior to v23.3, the specified Mercurial revision could\n be used to inject arbitrary configuration options to the \"hg clone\" \ncall (ie \"--config\"). Controlling the Mercurial configuration can modify\n how and which repository is installed. This vulnerability does not \naffect users who aren't installing from Mercurial.\n",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-77"
          ],
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 3.3
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 5.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 3.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 3.3
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2023-5752",
            "https://github.com/pypa/advisory-database/tree/main/vulns/pip/PYSEC-2023-228.yaml",
            "https://github.com/pypa/pip",
            "https://github.com/pypa/pip/commit/389cb799d0da9a840749fcd14878928467ed49b4",
            "https://github.com/pypa/pip/pull/12306",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-5752",
            "https://www.cve.org/CVERecord?id=CVE-2023-5752"
          ],
          "PublishedDate": "2023-10-25T18:17:44.867Z",
          "LastModifiedDate": "2023-11-03T14:55:50.973Z"
        },
        {
          "VulnerabilityID": "CVE-2022-24859",
          "PkgName": "pypdf2",
          "InstalledVersion": "1.26.0",
          "FixedVersion": "1.27.5",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-24859",
          "PkgRef": "pkg:pypi/pypdf2@1.26.0",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "PyPDF2: infinite loop vulnerability",
          "Description": "PyPDF2 is an open source python PDF library capable of splitting, merging, cropping, and transforming the pages of PDF files. In versions prior to 1.27.5 an attacker who uses this vulnerability can craft a PDF which leads to an infinite loop if the PyPDF2 if the code attempts to get the content stream. The reason is that the last while-loop in `ContentStream._readInlineImage` only terminates when it finds the `EI` token, but never actually checks if the stream has already ended. This issue has been resolved in version `1.27.5`. Users unable to upgrade should validate and PDFs prior to iterating over their content stream.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-835"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 6.2
            },
            "nvd": {
              "V2Vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
              "V2Score": 4.3,
              "V3Score": 5.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2022-24859",
            "https://github.com/py-pdf/PyPDF2",
            "https://github.com/py-pdf/PyPDF2/issues/329",
            "https://github.com/py-pdf/PyPDF2/pull/740",
            "https://github.com/py-pdf/PyPDF2/releases/tag/1.27.5",
            "https://github.com/py-pdf/PyPDF2/security/advisories/GHSA-xcjx-m2pj-8g79",
            "https://github.com/pypa/advisory-database/tree/main/vulns/pypdf2/PYSEC-2022-194.yaml",
            "https://lists.debian.org/debian-lts-announce/2022/06/msg00001.html",
            "https://lists.debian.org/debian-lts-announce/2023/06/msg00013.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-24859",
            "https://ubuntu.com/security/notices/USN-6176-1",
            "https://www.cve.org/CVERecord?id=CVE-2022-24859"
          ],
          "PublishedDate": "2022-04-18T19:15:09.757Z",
          "LastModifiedDate": "2023-06-10T01:15:52.347Z"
        },
        {
          "VulnerabilityID": "CVE-2023-36810",
          "PkgName": "pypdf2",
          "InstalledVersion": "1.26.0",
          "FixedVersion": "1.27.9",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-36810",
          "PkgRef": "pkg:pypi/pypdf2@1.26.0",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "pypdf is a pure-python PDF library capable of splitting, merging, crop ...",
          "Description": "pypdf is a pure-python PDF library capable of splitting, merging, cropping, and transforming the pages of PDF files. An attacker who uses this vulnerability can craft a PDF which leads to unexpected long runtime. This quadratic runtime blocks the current process and can utilize a single core of the CPU by 100%. It does not affect memory usage. This issue has been addressed in PR 808 and versions from 1.27.9 include this fix. Users are advised to upgrade. There are no known workarounds for this vulnerability.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-407"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 6.2
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
              "V3Score": 6.5
            }
          },
          "References": [
            "https://github.com/py-pdf/pypdf",
            "https://github.com/py-pdf/pypdf/commit/c6c56f550bb384e05f0139c796ba1308837d6373",
            "https://github.com/py-pdf/pypdf/issues/582",
            "https://github.com/py-pdf/pypdf/pull/808",
            "https://github.com/py-pdf/pypdf/security/advisories/GHSA-jrm6-h9cq-8gqw",
            "https://lists.debian.org/debian-lts-announce/2023/07/msg00019.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-36810",
            "https://ubuntu.com/security/notices/USN-6280-1",
            "https://www.cve.org/CVERecord?id=CVE-2023-36810"
          ],
          "PublishedDate": "2023-06-30T19:15:09.357Z",
          "LastModifiedDate": "2023-07-14T23:15:08.883Z"
        },
        {
          "VulnerabilityID": "CVE-2021-46823",
          "PkgName": "python-ldap",
          "InstalledVersion": "3.2.0",
          "FixedVersion": "3.4.0",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-46823",
          "PkgRef": "pkg:pypi/python-ldap@3.2.0",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-ldap: Regular expression denial of service in LDAP schema parser",
          "Description": "python-ldap before 3.4.0 is vulnerable to a denial of service when ldap.schema is used for untrusted schema definitions, because of a regular expression denial of service (ReDoS) flaw in the LDAP schema parser. By sending crafted regex input, a remote authenticated attacker could exploit this vulnerability to cause a denial of service condition.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-1333"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 6.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:S/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
              "V2Score": 4,
              "V3Score": 6.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 6.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2021-46823",
            "https://exchange.xforce.ibmcloud.com/vulnerabilities/221507",
            "https://github.com/python-ldap/python-ldap",
            "https://github.com/python-ldap/python-ldap/security/advisories/GHSA-r8wq-qrxc-hmcm",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-46823",
            "https://ubuntu.com/security/notices/USN-5508-1",
            "https://www.cve.org/CVERecord?id=CVE-2021-46823"
          ],
          "PublishedDate": "2022-06-18T16:15:08.173Z",
          "LastModifiedDate": "2023-08-08T14:22:24.967Z"
        },
        {
          "VulnerabilityID": "GHSA-r8wq-qrxc-hmcm",
          "PkgName": "python-ldap",
          "InstalledVersion": "3.2.0",
          "FixedVersion": "3.4.0",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://github.com/advisories/GHSA-r8wq-qrxc-hmcm",
          "PkgRef": "pkg:pypi/python-ldap@3.2.0",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "ReDoS in LDAP schema parser",
          "Description": "https://github.com/python-ldap/python-ldap/issues/424\n\n### Impact\nThe LDAP schema parser of python-ldap 3.3.1 and earlier are vulnerable to a regular expression denial-of-service attack. The issue affects clients that use ``ldap.schema`` package to parse LDAP schema definitions from an untrusted source.\n\n### Patches\nThe upcoming release of python-ldap 3.4.0 will contain a workaround to prevent ReDoS attacks. The schema parser refuses schema definitions with an excessive amount of backslashes.\n\n### Workarounds\nAs a workaround, users can check input for excessive amount of backslashes in schemas. More than a dozen backslashes per line are atypical.\n\n### References\n[CWE-1333](https://cwe.mitre.org/data/definitions/1333.html)\n\n### For more information\nIf you have any questions or comments about this advisory:\n* Open an issue in [python-ldap](https://github.com/python-ldap/python-ldap) tracker\n",
          "Severity": "MEDIUM",
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 6.5
            }
          },
          "References": [
            "https://github.com/python-ldap/python-ldap",
            "https://github.com/python-ldap/python-ldap/issues/424",
            "https://github.com/python-ldap/python-ldap/security/advisories/GHSA-r8wq-qrxc-hmcm"
          ]
        },
        {
          "VulnerabilityID": "CVE-2023-33733",
          "PkgName": "reportlab",
          "InstalledVersion": "3.6.8",
          "FixedVersion": "3.6.13",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-33733",
          "PkgRef": "pkg:pypi/reportlab@3.6.8",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-reportlab: remote code execution via supplying a crafted PDF file",
          "Description": "Reportlab up to v3.6.12 allows attackers to execute arbitrary code via supplying a crafted PDF file.",
          "Severity": "HIGH",
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 7.8
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 7.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 7.8
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2023-33733",
            "https://docs.reportlab.com/releases/notes/whats-new-3613/",
            "https://github.com/c53elyas/CVE-2023-33733",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/36WOY22ECJCPOXHVTNCHEWOQLL7JSWP4/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6ALE727IRACYBTTOFIFG57RS4OA2SHIJ/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/36WOY22ECJCPOXHVTNCHEWOQLL7JSWP4",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6ALE727IRACYBTTOFIFG57RS4OA2SHIJ",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-33733",
            "https://ubuntu.com/security/notices/USN-6196-1",
            "https://www.cve.org/CVERecord?id=CVE-2023-33733"
          ],
          "PublishedDate": "2023-06-05T16:15:09.55Z",
          "LastModifiedDate": "2023-11-07T04:15:24.363Z"
        },
        {
          "VulnerabilityID": "CVE-2023-32681",
          "PkgName": "requests",
          "InstalledVersion": "2.25.1",
          "FixedVersion": "2.31.0",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-32681",
          "PkgRef": "pkg:pypi/requests@2.25.1",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-requests: Unintended leak of Proxy-Authorization header",
          "Description": "Requests is a HTTP library. Since Requests 2.3.0, Requests has been leaking Proxy-Authorization headers to destination servers when redirected to an HTTPS endpoint. This is a product of how we use `rebuild_proxies` to reattach the `Proxy-Authorization` header to requests. For HTTP connections sent through the tunnel, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into the tunneled request. This results in Requests forwarding proxy credentials to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate sensitive information. This issue has been patched in version 2.31.0.\n\n",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-200"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
              "V3Score": 6.1
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
              "V3Score": 6.1
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
              "V3Score": 6.1
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:7050",
            "https://access.redhat.com/security/cve/CVE-2023-32681",
            "https://bugzilla.redhat.com/2209469",
            "https://bugzilla.redhat.com/263261",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2209469",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-32681",
            "https://errata.almalinux.org/8/ALSA-2023-7050.html",
            "https://errata.rockylinux.org/RLSA-2023:4520",
            "https://github.com/psf/requests",
            "https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5",
            "https://github.com/psf/requests/releases/tag/v2.31.0",
            "https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q",
            "https://github.com/pypa/advisory-database/tree/main/vulns/requests/PYSEC-2023-74.yaml",
            "https://linux.oracle.com/cve/CVE-2023-32681.html",
            "https://linux.oracle.com/errata/ELSA-2023-7050.html",
            "https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ/",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-32681",
            "https://security.gentoo.org/glsa/202309-08",
            "https://ubuntu.com/security/notices/USN-6155-1",
            "https://ubuntu.com/security/notices/USN-6155-2",
            "https://www.cve.org/CVERecord?id=CVE-2023-32681"
          ],
          "PublishedDate": "2023-05-26T18:15:14.147Z",
          "LastModifiedDate": "2023-09-17T09:15:12.327Z"
        },
        {
          "VulnerabilityID": "CVE-2022-40897",
          "PkgName": "setuptools",
          "InstalledVersion": "59.6.0",
          "FixedVersion": "65.5.1",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-40897",
          "PkgRef": "pkg:pypi/setuptools@59.6.0",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "pypa-setuptools: Regular Expression Denial of Service (ReDoS) in package_index.py",
          "Description": "Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-1333"
          ],
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:0835",
            "https://access.redhat.com/security/cve/CVE-2022-40897",
            "https://bugzilla.redhat.com/2158559",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2158559",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-40897",
            "https://errata.almalinux.org/8/ALSA-2023-0835.html",
            "https://errata.rockylinux.org/RLSA-2023:0952",
            "https://github.com/pypa/setuptools",
            "https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200",
            "https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be",
            "https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1",
            "https://github.com/pypa/setuptools/issues/3659",
            "https://linux.oracle.com/cve/CVE-2022-40897.html",
            "https://linux.oracle.com/errata/ELSA-2023-12348.html",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-40897",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
            "https://pyup.io/vulnerabilities/CVE-2022-40897/52495",
            "https://pyup.io/vulnerabilities/CVE-2022-40897/52495/",
            "https://security.netapp.com/advisory/ntap-20230214-0001",
            "https://security.netapp.com/advisory/ntap-20230214-0001/",
            "https://setuptools.pypa.io/en/latest",
            "https://ubuntu.com/security/notices/USN-5817-1",
            "https://www.cve.org/CVERecord?id=CVE-2022-40897"
          ],
          "PublishedDate": "2022-12-23T00:15:13.987Z",
          "LastModifiedDate": "2023-11-07T03:52:38.44Z"
        },
        {
          "VulnerabilityID": "CVE-2023-43804",
          "PkgName": "urllib3",
          "InstalledVersion": "1.26.5",
          "FixedVersion": "2.0.6, 1.26.17",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-43804",
          "PkgRef": "pkg:pypi/urllib3@1.26.5",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-urllib3: Cookie request header isn't stripped during cross-origin redirects",
          "Description": "urllib3 is a user-friendly HTTP client library for Python. urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly. This issue has been patched in urllib3 version 1.26.17 or 2.0.5.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-200"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N",
              "V3Score": 5.9
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
              "V3Score": 8.1
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N",
              "V3Score": 5.9
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2024:0133",
            "https://access.redhat.com/security/cve/CVE-2023-43804",
            "https://bugzilla.redhat.com/2226586",
            "https://bugzilla.redhat.com/2242493",
            "https://errata.almalinux.org/8/ALSA-2024-0133.html",
            "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-192.yaml",
            "https://github.com/urllib3/urllib3",
            "https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb",
            "https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d",
            "https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f",
            "https://linux.oracle.com/cve/CVE-2023-43804.html",
            "https://linux.oracle.com/errata/ELSA-2024-0464.html",
            "https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-43804",
            "https://ubuntu.com/security/notices/USN-6473-1",
            "https://ubuntu.com/security/notices/USN-6473-2",
            "https://www.cve.org/CVERecord?id=CVE-2023-43804"
          ],
          "PublishedDate": "2023-10-04T17:15:10.163Z",
          "LastModifiedDate": "2024-02-01T00:55:23.317Z"
        },
        {
          "VulnerabilityID": "CVE-2023-45803",
          "PkgName": "urllib3",
          "InstalledVersion": "1.26.5",
          "FixedVersion": "2.0.7, 1.26.18",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-45803",
          "PkgRef": "pkg:pypi/urllib3@1.26.5",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "urllib3: Request body not stripped after redirect from 303 status changes request method to GET",
          "Description": "urllib3 is a user-friendly HTTP client library for Python. urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 301, 302, or 303 after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although this behavior is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers. Because the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable. Both of the following conditions must be true to be affected by this vulnerability: 1. Using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON) and 2. The origin service is compromised and starts redirecting using 301, 302, or 303 to a malicious peer or the redirected-to service becomes compromised. This issue has been addressed in versions 1.26.18 and 2.0.7 and users are advised to update to resolve this issue. Users unable to update should disable redirects for services that aren't expecting to respond with redirects with `redirects=False` and disable automatic redirects with `redirects=False` and handle 301, 302, and 303 redirects manually by stripping the HTTP request body.\n",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-200"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 4.2
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 4.2
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 4.2
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2024:0116",
            "https://access.redhat.com/security/cve/CVE-2023-45803",
            "https://bugzilla.redhat.com/2242493",
            "https://bugzilla.redhat.com/2246840",
            "https://errata.almalinux.org/8/ALSA-2024-0116.html",
            "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-212.yaml",
            "https://github.com/urllib3/urllib3",
            "https://github.com/urllib3/urllib3/commit/4e50fbc5db74e32cabd5ccc1ab81fc103adfe0b3",
            "https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9",
            "https://github.com/urllib3/urllib3/commit/b594c5ceaca38e1ac215f916538fb128e3526a36",
            "https://github.com/urllib3/urllib3/releases/tag/1.26.18",
            "https://github.com/urllib3/urllib3/releases/tag/2.0.7",
            "https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4",
            "https://linux.oracle.com/cve/CVE-2023-45803.html",
            "https://linux.oracle.com/errata/ELSA-2024-0464.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-45803",
            "https://ubuntu.com/security/notices/USN-6473-1",
            "https://ubuntu.com/security/notices/USN-6473-2",
            "https://www.cve.org/CVERecord?id=CVE-2023-45803",
            "https://www.rfc-editor.org/rfc/rfc9110.html#name-get"
          ],
          "PublishedDate": "2023-10-17T20:15:10.07Z",
          "LastModifiedDate": "2023-11-03T22:15:11.693Z"
        },
        {
          "VulnerabilityID": "CVE-2023-25577",
          "PkgName": "werkzeug",
          "InstalledVersion": "2.0.2",
          "FixedVersion": "2.2.3",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-25577",
          "PkgRef": "pkg:pypi/werkzeug@2.0.2",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-werkzeug: high resource usage when parsing multipart form data with many fields",
          "Description": "Werkzeug is a comprehensive WSGI web application library. Prior to version 2.2.3, Werkzeug's multipart form data parser will parse an unlimited number of parts, including file parts. Parts can be a small amount of bytes, but each requires CPU time to parse and may use more memory as Python data. If a request can be made to an endpoint that accesses `request.data`, `request.form`, `request.files`, or `request.get_data(parse_form_data=False)`, it can cause unexpectedly high resource usage. This allows an attacker to cause a denial of service by sending crafted multipart data to an endpoint that will parse it. The amount of CPU time required can block worker processes from handling legitimate requests. The amount of RAM required can trigger an out of memory kill of the process. Unlimited file parts can use up memory and file handles. If many concurrent requests are sent continuously, this can exhaust or kill all available workers. Version 2.2.3 contains a patch for this issue.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-770"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2023-25577",
            "https://github.com/pallets/werkzeug",
            "https://github.com/pallets/werkzeug/commit/517cac5a804e8c4dc4ed038bb20dacd038e7a9f1",
            "https://github.com/pallets/werkzeug/releases/tag/2.2.3",
            "https://github.com/pallets/werkzeug/security/advisories/GHSA-xg9f-g7g7-2323",
            "https://linux.oracle.com/cve/CVE-2023-25577.html",
            "https://linux.oracle.com/errata/ELSA-2023-12709.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-25577",
            "https://security.netapp.com/advisory/ntap-20230818-0003",
            "https://security.netapp.com/advisory/ntap-20230818-0003/",
            "https://ubuntu.com/security/notices/USN-5948-1",
            "https://ubuntu.com/security/notices/USN-5948-2",
            "https://www.cve.org/CVERecord?id=CVE-2023-25577",
            "https://www.debian.org/security/2023/dsa-5470"
          ],
          "PublishedDate": "2023-02-14T20:15:17.543Z",
          "LastModifiedDate": "2023-08-18T14:15:21.097Z"
        },
        {
          "VulnerabilityID": "CVE-2023-46136",
          "PkgName": "werkzeug",
          "InstalledVersion": "2.0.2",
          "FixedVersion": "3.0.1, 2.3.8",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-46136",
          "PkgRef": "pkg:pypi/werkzeug@2.0.2",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-werkzeug: high resource consumption leading to denial of service",
          "Description": "Werkzeug is a comprehensive WSGI web application library. If an upload of a file that starts with CR or LF and then is followed by megabytes of data without these characters: all of these bytes are appended chunk by chunk into internal bytearray and lookup for boundary is performed on growing buffer. This allows an attacker to cause a denial of service by sending crafted multipart data to an endpoint that will parse it. The amount of CPU time required can block worker processes from handling legitimate requests. This vulnerability has been patched in version 3.0.1.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-787",
            "CWE-400",
            "CWE-407"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.7
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2023-46136",
            "https://github.com/pallets/werkzeug",
            "https://github.com/pallets/werkzeug/commit/b1916c0c083e0be1c9d887ee2f3d696922bfc5c1",
            "https://github.com/pallets/werkzeug/commit/f2300208d5e2a5076cbbb4c2aad71096fd040ef9",
            "https://github.com/pallets/werkzeug/commit/f3c803b3ade485a45f12b6d6617595350c0f03e2",
            "https://github.com/pallets/werkzeug/security/advisories/GHSA-hrfv-mqp8-q5rw",
            "https://github.com/pypa/advisory-database/tree/main/vulns/werkzeug/PYSEC-2023-221.yaml",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-46136",
            "https://security.netapp.com/advisory/ntap-20231124-0008",
            "https://security.netapp.com/advisory/ntap-20231124-0008/",
            "https://www.cve.org/CVERecord?id=CVE-2023-46136"
          ],
          "PublishedDate": "2023-10-25T18:17:36.753Z",
          "LastModifiedDate": "2024-01-10T18:58:41.083Z"
        },
        {
          "VulnerabilityID": "CVE-2023-23934",
          "PkgName": "werkzeug",
          "InstalledVersion": "2.0.2",
          "FixedVersion": "2.2.3",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-23934",
          "PkgRef": "pkg:pypi/werkzeug@2.0.2",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-werkzeug: cookie prefixed with = can shadow unprefixed cookie",
          "Description": "Werkzeug is a comprehensive WSGI web application library. Browsers may allow \"nameless\" cookies that look like `=value` instead of `key=value`. A vulnerable browser may allow a compromised application on an adjacent subdomain to exploit this to set a cookie like `=__Host-test=bad` for another subdomain. Werkzeug prior to 2.2.3 will parse the cookie `=__Host-test=bad` as __Host-test=bad`. If a Werkzeug application is running next to a vulnerable or malicious subdomain which sets such a cookie using a vulnerable browser, the Werkzeug application will see the bad cookie value but the valid cookie key. The issue is fixed in Werkzeug 2.2.3.",
          "Severity": "LOW",
          "CweIDs": [
            "CWE-20"
          ],
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:A/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:N",
              "V3Score": 2.6
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:A/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N",
              "V3Score": 3.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:A/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:N",
              "V3Score": 2.6
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2023-23934",
            "https://github.com/pallets/werkzeug",
            "https://github.com/pallets/werkzeug/commit/cf275f42acad1b5950c50ffe8ef58fe62cdce028",
            "https://github.com/pallets/werkzeug/releases/tag/2.2.3",
            "https://github.com/pallets/werkzeug/security/advisories/GHSA-px8h-6qxv-m22q",
            "https://linux.oracle.com/cve/CVE-2023-23934.html",
            "https://linux.oracle.com/errata/ELSA-2023-12709.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-23934",
            "https://security.netapp.com/advisory/ntap-20230818-0003",
            "https://security.netapp.com/advisory/ntap-20230818-0003/",
            "https://ubuntu.com/security/notices/USN-5948-1",
            "https://ubuntu.com/security/notices/USN-5948-2",
            "https://www.cve.org/CVERecord?id=CVE-2023-23934",
            "https://www.debian.org/security/2023/dsa-5470"
          ],
          "PublishedDate": "2023-02-14T20:15:17.37Z",
          "LastModifiedDate": "2023-08-18T14:15:20.553Z"
        },
        {
          "VulnerabilityID": "CVE-2022-40898",
          "PkgName": "wheel",
          "InstalledVersion": "0.37.1",
          "FixedVersion": "0.38.1",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-40898",
          "PkgRef": "pkg:pypi/wheel@0.37.1",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-wheel: remote attackers can cause denial of service via attacker controlled input to wheel cli",
          "Description": "An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli.",
          "Severity": "HIGH",
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:6712",
            "https://access.redhat.com/security/cve/CVE-2022-40898",
            "https://bugzilla.redhat.com/2165864",
            "https://errata.almalinux.org/9/ALSA-2023-6712.html",
            "https://github.com/pypa/wheel",
            "https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18",
            "https://github.com/pypa/wheel/commit/88f02bc335d5404991e532e7f3b0fc80437bf4e0",
            "https://linux.oracle.com/cve/CVE-2022-40898.html",
            "https://linux.oracle.com/errata/ELSA-2023-6712.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-40898",
            "https://pypi.org/project/wheel",
            "https://pypi.org/project/wheel/",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
            "https://pyup.io/vulnerabilities/CVE-2022-40898/51499",
            "https://ubuntu.com/security/notices/USN-5821-1",
            "https://ubuntu.com/security/notices/USN-5821-2",
            "https://www.cve.org/CVERecord?id=CVE-2022-40898"
          ],
          "PublishedDate": "2022-12-23T00:15:14.043Z",
          "LastModifiedDate": "2022-12-30T22:15:22.8Z"
        }
      ]
    }
  ]
}
