{"id": "CVE-2021-3572", "package": "pypi:pip", "purl": "pkg:pypi/pip@20.2.4", "package_type": "pypi", "package_usage": "N/A", "version": "20.2.4", "fix_version": "21.1", "severity": "MEDIUM", "cvss_score": "5.7", "short_description": "# Improper Input Validation in pip\nA flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity. This is fixed in python-pip version 21.1.\n\n## Related CVE(s)\nBIT-pip-2021-3572, CVE-2021-3572, PYSEC-2021-437", "related_urls": ["https://nvd.nist.gov/vuln/detail/CVE-2021-3572", "https://github.com/pypa/pip/pull/9827", "https://github.com/pypa/pip/commit/e46bdda9711392fec0c45c1175bae6db847cb30b", "https://access.redhat.com/errata/RHSA-2021:3254", "https://bugzilla.redhat.com/show_bug.cgi?id=1962856", "https://github.com/pypa/pip", "https://packetstormsecurity.com/files/162712/USN-4961-1.txt", "https://www.oracle.com/security-alerts/cpuapr2022.html", "https://www.oracle.com/security-alerts/cpujul2022.html"], "occurrence_count": 0, "reachable_flows": 0}
{"id": "CVE-2022-40897", "package": "pypi:setuptools", "purl": "pkg:pypi/setuptools@50.3.2", "package_type": "pypi", "package_usage": "N/A", "version": "50.3.2", "fix_version": "65.5.1", "severity": "HIGH", "cvss_score": "7.5", "short_description": "# pypa/setuptools vulnerable to Regular Expression Denial of Service (ReDoS)\nPython Packaging Authority (PyPA)'s setuptools is a library designed to facilitate packaging Python projects. Setuptools version 65.5.0 and earlier could allow remote attackers to cause a denial of service by fetching malicious HTML from a PyPI package or custom PackageIndex page due to a vulnerable Regular Expression in `package_index`. This has been patched in version 65.5.1.\n\n## Related CVE(s)\nBIT-setuptools-2022-40897, CVE-2022-40897, PYSEC-2022-43012", "related_urls": ["https://nvd.nist.gov/vuln/detail/CVE-2022-40897", "https://github.com/pypa/setuptools/issues/3659", "https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be", "https://github.com/pypa/setuptools", "https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200", "https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H", "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages", "https://pyup.io/vulnerabilities/CVE-2022-40897/52495", "https://security.netapp.com/advisory/ntap-20230214-0001", "https://setuptools.pypa.io/en/latest"], "occurrence_count": 0, "reachable_flows": 0}
{"id": "CVE-2022-40897", "package": "python:setuptools", "purl": "python:setuptools", "package_type": "python", "package_usage": "N/A", "version": null, "fix_version": "65.5.1", "severity": "MEDIUM", "cvss_score": "5.9", "short_description": "Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.", "related_urls": ["https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200", "https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be", "https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/", "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/", "https://pyup.io/vulnerabilities/CVE-2022-40897/52495/", "https://security.netapp.com/advisory/ntap-20230214-0001/"], "occurrence_count": 0, "reachable_flows": 0}
{"id": "CVE-2023-5752", "package": "pypi:pip", "purl": "pkg:pypi/pip@20.2.4", "package_type": "pypi", "package_usage": "N/A", "version": "20.2.4", "fix_version": "23.3", "severity": "MEDIUM", "cvss_score": "5.5", "short_description": "# Command Injection in pip when used with Mercurial\nWhen installing a package from a Mercurial VCS URL, e.g. `pip install hg+...`, with pip prior to v23.3, the specified Mercurial revision could be used to inject arbitrary configuration options to the `hg clone` call (e.g. `--config`). Controlling the Mercurial configuration can modify how and which repository is installed. This vulnerability does not affect users who aren't installing from Mercurial.\n\n## Related CVE(s)\nBIT-pip-2023-5752, CVE-2023-5752, PYSEC-2023-228", "related_urls": ["https://nvd.nist.gov/vuln/detail/CVE-2023-5752", "https://github.com/pypa/pip/pull/12306", "https://github.com/pypa/pip/commit/389cb799d0da9a840749fcd14878928467ed49b4", "https://github.com/pypa/advisory-database/tree/main/vulns/pip/PYSEC-2023-228.yaml", "https://github.com/pypa/pip", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ", "https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL"], "occurrence_count": 0, "reachable_flows": 0}
