{
 "matches": [
  {
   "vulnerability": {
    "id": "GHSA-6vqw-3v5j-54x4",
    "dataSource": "https://github.com/advisories/GHSA-6vqw-3v5j-54x4",
    "namespace": "github:language:python",
    "severity": "High",
    "urls": [
     "https://github.com/advisories/GHSA-6vqw-3v5j-54x4"
    ],
    "description": "cryptography NULL pointer dereference with pkcs12.serialize_key_and_certificates when called with a non-matching certificate and private key and an hmac_hash override",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "metrics": {
       "baseScore": 7.5,
       "exploitabilityScore": 3.9,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "High",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "42.0.4"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2024-26130",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-26130",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://github.com/pyca/cryptography/commit/97d231672763cdb5959a3b191e692a362f1b9e55",
      "https://github.com/pyca/cryptography/pull/10423",
      "https://github.com/pyca/cryptography/security/advisories/GHSA-6vqw-3v5j-54x4"
     ],
     "description": "cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Starting in version 38.0.0 and prior to version 42.0.4, if `pkcs12.serialize_key_and_certificates` is called with both a certificate whose public key did not match the provided private key and an `encryption_algorithm` with `hmac_hash` set (via `PrivateFormat.PKCS12.encryption_builder().hmac_hash(...)`, then a NULL pointer dereference would occur, crashing the Python process. This has been resolved in version 42.0.4, the first version in which a `ValueError` is properly raised.",
     "cvss": [
      {
       "source": "security-advisories@github.com",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "cryptography",
       "version": "41.0.7"
      }
     },
     "found": {
      "versionConstraint": ">=38.0.0,<42.0.4 (python)",
      "vulnerabilityID": "GHSA-6vqw-3v5j-54x4"
     }
    }
   ],
   "artifact": {
    "id": "d7c64da7936accc1",
    "name": "cryptography",
    "version": "41.0.7",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "Apache-2.0 OR BSD-3-Clause"
    ],
    "cpes": [],
    "purl": "pkg:pypi/cryptography@41.0.7",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-3ww4-gg4f-jr7f",
    "dataSource": "https://github.com/advisories/GHSA-3ww4-gg4f-jr7f",
    "namespace": "github:language:python",
    "severity": "High",
    "urls": [
     "https://github.com/advisories/GHSA-3ww4-gg4f-jr7f"
    ],
    "description": "Python Cryptography package vulnerable to Bleichenbacher timing oracle attack",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "metrics": {
       "baseScore": 7.5,
       "exploitabilityScore": 3.9,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "High",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "42.0.0"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-50782",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-50782",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://access.redhat.com/security/cve/CVE-2023-50782",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2254432"
     ],
     "description": "A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      },
      {
       "source": "secalert@redhat.com",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "cryptography",
       "version": "41.0.7"
      }
     },
     "found": {
      "versionConstraint": "<42.0.0 (python)",
      "vulnerabilityID": "GHSA-3ww4-gg4f-jr7f"
     }
    }
   ],
   "artifact": {
    "id": "d7c64da7936accc1",
    "name": "cryptography",
    "version": "41.0.7",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "Apache-2.0 OR BSD-3-Clause"
    ],
    "cpes": [],
    "purl": "pkg:pypi/cryptography@41.0.7",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-9v9h-cgj8-h64p",
    "dataSource": "https://github.com/advisories/GHSA-9v9h-cgj8-h64p",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-9v9h-cgj8-h64p"
    ],
    "description": "Null pointer dereference in PKCS12 parsing",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
      "metrics": {
       "baseScore": 5.5,
       "exploitabilityScore": 1.8,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "42.0.2"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2024-0727",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-0727",
     "namespace": "nvd:cpe",
     "severity": "Medium",
     "urls": [
      "https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2",
      "https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a",
      "https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c",
      "https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8",
      "https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539",
      "https://security.netapp.com/advisory/ntap-20240208-0006/",
      "https://www.openssl.org/news/secadv/20240125.txt"
     ],
     "description": "Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 5.5,
        "exploitabilityScore": 1.8,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "cryptography",
       "version": "41.0.7"
      }
     },
     "found": {
      "versionConstraint": "<42.0.2 (python)",
      "vulnerabilityID": "GHSA-9v9h-cgj8-h64p"
     }
    }
   ],
   "artifact": {
    "id": "d7c64da7936accc1",
    "name": "cryptography",
    "version": "41.0.7",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "Apache-2.0 OR BSD-3-Clause"
    ],
    "cpes": [],
    "purl": "pkg:pypi/cryptography@41.0.7",
    "upstreams": []
   }
  }
 ],
 "source": {
  "type": "image",
  "target": {
   "userInput": "",
   "imageID": "",
   "manifestDigest": "",
   "mediaType": "",
   "tags": [],
   "imageSize": 0,
   "layers": null,
   "manifest": null,
   "config": null,
   "repoDigests": [],
   "architecture": "",
   "os": ""
  }
 },
 "distro": {
  "name": "",
  "version": "",
  "idLike": null
 },
 "descriptor": {
  "name": "grype",
  "version": "0.74.0",
  "configuration": {
   "output": [
    "json"
   ],
   "file": "",
   "distro": "",
   "add-cpes-if-none": false,
   "output-template-file": "",
   "check-for-app-update": true,
   "only-fixed": false,
   "only-notfixed": false,
   "ignore-wontfix": "",
   "platform": "",
   "search": {
    "scope": "squashed",
    "unindexed-archives": false,
    "indexed-archives": true
   },
   "ignore": null,
   "exclude": [],
   "db": {
    "cache-dir": "/Users/katushka/Library/Caches/grype/db",
    "update-url": "https://toolbox-data.anchore.io/grype/databases/listing.json",
    "ca-cert": "",
    "auto-update": true,
    "validate-by-hash-on-start": false,
    "validate-age": true,
    "max-allowed-built-age": 432000000000000
   },
   "externalSources": {
    "enable": false,
    "maven": {
     "searchUpstreamBySha1": true,
     "baseUrl": "https://search.maven.org/solrsearch/select"
    }
   },
   "match": {
    "java": {
     "using-cpes": false
    },
    "dotnet": {
     "using-cpes": false
    },
    "golang": {
     "using-cpes": false,
     "always-use-cpe-for-stdlib": true
    },
    "javascript": {
     "using-cpes": false
    },
    "python": {
     "using-cpes": false
    },
    "ruby": {
     "using-cpes": false
    },
    "rust": {
     "using-cpes": false
    },
    "stock": {
     "using-cpes": true
    }
   },
   "fail-on-severity": "",
   "registry": {
    "insecure-skip-tls-verify": false,
    "insecure-use-http": false,
    "auth": null,
    "ca-cert": ""
   },
   "show-suppressed": false,
   "by-cve": false,
   "name": "",
   "default-image-pull-source": "",
   "vex-documents": [],
   "vex-add": []
  },
  "db": {
   "built": "2024-04-20T01:25:41Z",
   "schemaVersion": 5,
   "location": "/Users/katushka/Library/Caches/grype/db/5",
   "checksum": "sha256:16b261c20c43828088d3530bdb10577ad87b9d33cfbfcaf051c3af61ba7e53ca",
   "error": null
  },
  "timestamp": "2024-04-20T21:50:36.097488+02:00"
 }
}
