{
 "matches": [
  {
   "vulnerability": {
    "id": "GHSA-h4m5-qpfp-3mpv",
    "dataSource": "https://github.com/advisories/GHSA-h4m5-qpfp-3mpv",
    "namespace": "github:language:python",
    "severity": "High",
    "urls": [
     "https://github.com/advisories/GHSA-h4m5-qpfp-3mpv"
    ],
    "description": "Directory Traversal in Babel",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
      "metrics": {
       "baseScore": 7.8,
       "exploitabilityScore": 1.8,
       "impactScore": 5.9
      },
      "vendorMetadata": {
       "base_severity": "High",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "2.9.1"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2021-42771",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2021-42771",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://github.com/python-babel/babel/pull/782",
      "https://lists.debian.org/debian-lts-announce/2021/10/msg00018.html",
      "https://lists.debian.org/debian-lts/2021/10/msg00040.html",
      "https://www.debian.org/security/2021/dsa-5018",
      "https://www.tenable.com/security/research/tra-2021-14"
     ],
     "description": "Babel.Locale in Babel before 2.9.1 allows attackers to load arbitrary locale .dat files (containing serialized Python objects) via directory traversal, leading to code execution.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "2.0",
       "vector": "AV:L/AC:L/Au:N/C:C/I:C/A:C",
       "metrics": {
        "baseScore": 7.2,
        "exploitabilityScore": 3.9,
        "impactScore": 10
       },
       "vendorMetadata": {}
      },
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
       "metrics": {
        "baseScore": 7.8,
        "exploitabilityScore": 1.8,
        "impactScore": 5.9
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "babel",
       "version": "2.8.0"
      }
     },
     "found": {
      "versionConstraint": "<2.9.1 (python)",
      "vulnerabilityID": "GHSA-h4m5-qpfp-3mpv"
     }
    }
   ],
   "artifact": {
    "id": "7b8228262312ebfa",
    "name": "babel",
    "version": "2.8.0",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "BSD"
    ],
    "cpes": [],
    "purl": "pkg:pypi/babel@2.8.0",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-xqr8-7jwr-rhp7",
    "dataSource": "https://github.com/advisories/GHSA-xqr8-7jwr-rhp7",
    "namespace": "github:language:python",
    "severity": "High",
    "urls": [
     "https://github.com/advisories/GHSA-xqr8-7jwr-rhp7"
    ],
    "description": "Removal of e-Tugra root certificate",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
      "metrics": {
       "baseScore": 7.5,
       "exploitabilityScore": 3.9,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "High",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "2023.7.22"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-37920",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-37920",
     "namespace": "nvd:cpe",
     "severity": "Critical",
     "urls": [
      "https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909",
      "https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7",
      "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/"
     ],
     "description": "Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi prior to version 2023.07.22 recognizes \"e-Tugra\" root certificates. e-Tugra's root certificates were subject to an investigation prompted by reporting of security issues in their systems. Certifi 2023.07.22 removes root certificates from \"e-Tugra\" from the root store.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
       "metrics": {
        "baseScore": 9.8,
        "exploitabilityScore": 3.9,
        "impactScore": 5.9
       },
       "vendorMetadata": {}
      },
      {
       "source": "security-advisories@github.com",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "certifi",
       "version": "2020.6.20"
      }
     },
     "found": {
      "versionConstraint": ">=2015.4.28,<2023.7.22 (python)",
      "vulnerabilityID": "GHSA-xqr8-7jwr-rhp7"
     }
    }
   ],
   "artifact": {
    "id": "dd55b74a066559c6",
    "name": "certifi",
    "version": "2020.6.20",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "MPL-2.0"
    ],
    "cpes": [],
    "purl": "pkg:pypi/certifi@2020.6.20",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-43fp-rhv2-5gv8",
    "dataSource": "https://github.com/advisories/GHSA-43fp-rhv2-5gv8",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-43fp-rhv2-5gv8"
    ],
    "description": "Certifi removing TrustCor root certificate",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:N/I:H/A:N",
      "metrics": {
       "baseScore": 6.8,
       "exploitabilityScore": 2.3,
       "impactScore": 4
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "2022.12.07"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2022-23491",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2022-23491",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://github.com/certifi/python-certifi/security/advisories/GHSA-43fp-rhv2-5gv8",
      "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ"
     ],
     "description": "Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi 2022.12.07 removes root certificates from \"TrustCor\" from the root store. These are in the process of being removed from Mozilla's trust store. TrustCor's root certificates are being removed pursuant to an investigation prompted by media reporting that TrustCor's ownership also operated a business that produced spyware. Conclusions of Mozilla's investigation can be found in the linked google group discussion.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      },
      {
       "source": "security-advisories@github.com",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:N/I:H/A:N",
       "metrics": {
        "baseScore": 6.8,
        "exploitabilityScore": 2.3,
        "impactScore": 4
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "certifi",
       "version": "2020.6.20"
      }
     },
     "found": {
      "versionConstraint": ">=2017.11.05,<2022.12.07 (python)",
      "vulnerabilityID": "GHSA-43fp-rhv2-5gv8"
     }
    }
   ],
   "artifact": {
    "id": "dd55b74a066559c6",
    "name": "certifi",
    "version": "2020.6.20",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "MPL-2.0"
    ],
    "cpes": [],
    "purl": "pkg:pypi/certifi@2020.6.20",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-x4qr-2fvf-3mr5",
    "dataSource": "https://github.com/advisories/GHSA-x4qr-2fvf-3mr5",
    "namespace": "github:language:python",
    "severity": "High",
    "urls": [
     "https://github.com/advisories/GHSA-x4qr-2fvf-3mr5"
    ],
    "description": "Vulnerable OpenSSL included in cryptography wheels",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H",
      "metrics": {
       "baseScore": 7.4,
       "exploitabilityScore": 2.2,
       "impactScore": 5.2
      },
      "vendorMetadata": {
       "base_severity": "High",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "39.0.1"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-0286",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-0286",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.6.2-relnotes.txt",
      "https://ftp.openbsd.org/pub/OpenBSD/patches/7.2/common/018_x509.patch.sig",
      "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2c6c9d439b484e1ba9830d8454a34fa4f80fdfe9",
      "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2f7530077e0ef79d98718138716bc51ca0cad658",
      "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=fd2af07dc083a350c959147097003a14a5e8ac4d",
      "https://security.gentoo.org/glsa/202402-08",
      "https://www.openssl.org/news/secadv/20230207.txt"
     ],
     "description": "There is a type confusion vulnerability relating to X.400 address processing\ninside an X.509 GeneralName. X.400 addresses were parsed as an ASN1_STRING but\nthe public structure definition for GENERAL_NAME incorrectly specified the type\nof the x400Address field as ASN1_TYPE. This field is subsequently interpreted by\nthe OpenSSL function GENERAL_NAME_cmp as an ASN1_TYPE rather than an\nASN1_STRING.\n\nWhen CRL checking is enabled (i.e. the application sets the\nX509_V_FLAG_CRL_CHECK flag), this vulnerability may allow an attacker to pass\narbitrary pointers to a memcmp call, enabling them to read memory contents or\nenact a denial of service. In most cases, the attack requires the attacker to\nprovide both the certificate chain and CRL, neither of which need to have a\nvalid signature. If the attacker only controls one of these inputs, the other\ninput must already contain an X.400 address as a CRL distribution point, which\nis uncommon. As such, this vulnerability is most likely to only affect\napplications which have implemented their own functionality for retrieving CRLs\nover a network.\n\n",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H",
       "metrics": {
        "baseScore": 7.4,
        "exploitabilityScore": 2.2,
        "impactScore": 5.2
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "cryptography",
       "version": "3.4.8"
      }
     },
     "found": {
      "versionConstraint": ">=0.8.1,<39.0.1 (python)",
      "vulnerabilityID": "GHSA-x4qr-2fvf-3mr5"
     }
    }
   ],
   "artifact": {
    "id": "5c06ada74268d17c",
    "name": "cryptography",
    "version": "3.4.8",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "BSD OR Apache License, Version 2.0"
    ],
    "cpes": [],
    "purl": "pkg:pypi/cryptography@3.4.8",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-3ww4-gg4f-jr7f",
    "dataSource": "https://github.com/advisories/GHSA-3ww4-gg4f-jr7f",
    "namespace": "github:language:python",
    "severity": "High",
    "urls": [
     "https://github.com/advisories/GHSA-3ww4-gg4f-jr7f"
    ],
    "description": "Python Cryptography package vulnerable to Bleichenbacher timing oracle attack",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "metrics": {
       "baseScore": 7.5,
       "exploitabilityScore": 3.9,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "High",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "42.0.0"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-50782",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-50782",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://access.redhat.com/security/cve/CVE-2023-50782",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2254432"
     ],
     "description": "A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      },
      {
       "source": "secalert@redhat.com",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "cryptography",
       "version": "3.4.8"
      }
     },
     "found": {
      "versionConstraint": "<42.0.0 (python)",
      "vulnerabilityID": "GHSA-3ww4-gg4f-jr7f"
     }
    }
   ],
   "artifact": {
    "id": "5c06ada74268d17c",
    "name": "cryptography",
    "version": "3.4.8",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "BSD OR Apache License, Version 2.0"
    ],
    "cpes": [],
    "purl": "pkg:pypi/cryptography@3.4.8",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-w7pp-m8wf-vj6r",
    "dataSource": "https://github.com/advisories/GHSA-w7pp-m8wf-vj6r",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-w7pp-m8wf-vj6r"
    ],
    "description": "Cipher.update_into can corrupt memory if passed an immutable python object as the outbuf",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L",
      "metrics": {
       "baseScore": 6.5,
       "exploitabilityScore": 3.9,
       "impactScore": 2.5
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "39.0.1"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-23931",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-23931",
     "namespace": "nvd:cpe",
     "severity": "Medium",
     "urls": [
      "https://github.com/pyca/cryptography/pull/8230/commits/94a50a9731f35405f0357fa5f3b177d46a726ab3",
      "https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r"
     ],
     "description": "cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. In affected versions `Cipher.update_into` would accept Python objects which implement the buffer protocol, but provide only immutable buffers. This would allow immutable objects (such as `bytes`) to be mutated, thus violating fundamental rules of Python and resulting in corrupted output. This now correctly raises an exception. This issue has been present since `update_into` was originally introduced in cryptography 1.8.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L",
       "metrics": {
        "baseScore": 6.5,
        "exploitabilityScore": 3.9,
        "impactScore": 2.5
       },
       "vendorMetadata": {}
      },
      {
       "source": "security-advisories@github.com",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:L",
       "metrics": {
        "baseScore": 4.8,
        "exploitabilityScore": 2.2,
        "impactScore": 2.5
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "cryptography",
       "version": "3.4.8"
      }
     },
     "found": {
      "versionConstraint": ">=1.8,<39.0.1 (python)",
      "vulnerabilityID": "GHSA-w7pp-m8wf-vj6r"
     }
    }
   ],
   "artifact": {
    "id": "5c06ada74268d17c",
    "name": "cryptography",
    "version": "3.4.8",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "BSD OR Apache License, Version 2.0"
    ],
    "cpes": [],
    "purl": "pkg:pypi/cryptography@3.4.8",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-jfhm-5ghh-2f97",
    "dataSource": "https://github.com/advisories/GHSA-jfhm-5ghh-2f97",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-jfhm-5ghh-2f97"
    ],
    "description": "cryptography vulnerable to NULL-dereference when loading PKCS7 certificates",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "metrics": {
       "baseScore": 5.9,
       "exploitabilityScore": 2.2,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "41.0.6"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-49083",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-49083",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://github.com/pyca/cryptography/commit/f09c261ca10a31fe41b1262306db7f8f1da0e48a",
      "https://github.com/pyca/cryptography/pull/9926",
      "https://github.com/pyca/cryptography/security/advisories/GHSA-jfhm-5ghh-2f97",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QMNTYMUGFJSDBYBU22FUYBHFRZODRKXV/"
     ],
     "description": "cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Calling `load_pem_pkcs7_certificates` or `load_der_pkcs7_certificates` could lead to a NULL-pointer dereference and segfault. Exploitation of this vulnerability poses a serious risk of Denial of Service (DoS) for any application attempting to deserialize a PKCS7 blob/certificate. The consequences extend to potential disruptions in system availability and stability. This vulnerability has been patched in version 41.0.6.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      },
      {
       "source": "security-advisories@github.com",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 5.9,
        "exploitabilityScore": 2.2,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "cryptography",
       "version": "3.4.8"
      }
     },
     "found": {
      "versionConstraint": ">=3.1,<41.0.6 (python)",
      "vulnerabilityID": "GHSA-jfhm-5ghh-2f97"
     }
    }
   ],
   "artifact": {
    "id": "5c06ada74268d17c",
    "name": "cryptography",
    "version": "3.4.8",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "BSD OR Apache License, Version 2.0"
    ],
    "cpes": [],
    "purl": "pkg:pypi/cryptography@3.4.8",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-9v9h-cgj8-h64p",
    "dataSource": "https://github.com/advisories/GHSA-9v9h-cgj8-h64p",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-9v9h-cgj8-h64p"
    ],
    "description": "Null pointer dereference in PKCS12 parsing",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
      "metrics": {
       "baseScore": 5.5,
       "exploitabilityScore": 1.8,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "42.0.2"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2024-0727",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-0727",
     "namespace": "nvd:cpe",
     "severity": "Medium",
     "urls": [
      "https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2",
      "https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a",
      "https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c",
      "https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8",
      "https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539",
      "https://security.netapp.com/advisory/ntap-20240208-0006/",
      "https://www.openssl.org/news/secadv/20240125.txt"
     ],
     "description": "Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 5.5,
        "exploitabilityScore": 1.8,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "cryptography",
       "version": "3.4.8"
      }
     },
     "found": {
      "versionConstraint": "<42.0.2 (python)",
      "vulnerabilityID": "GHSA-9v9h-cgj8-h64p"
     }
    }
   ],
   "artifact": {
    "id": "5c06ada74268d17c",
    "name": "cryptography",
    "version": "3.4.8",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "BSD OR Apache License, Version 2.0"
    ],
    "cpes": [],
    "purl": "pkg:pypi/cryptography@3.4.8",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-v8gr-m533-ghj9",
    "dataSource": "https://github.com/advisories/GHSA-v8gr-m533-ghj9",
    "namespace": "github:language:python",
    "severity": "Low",
    "urls": [
     "https://github.com/advisories/GHSA-v8gr-m533-ghj9"
    ],
    "description": "Vulnerable OpenSSL included in cryptography wheels",
    "cvss": [],
    "fix": {
     "versions": [
      "41.0.4"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "cryptography",
       "version": "3.4.8"
      }
     },
     "found": {
      "versionConstraint": ">=2.5,<41.0.4 (python)",
      "vulnerabilityID": "GHSA-v8gr-m533-ghj9"
     }
    }
   ],
   "artifact": {
    "id": "5c06ada74268d17c",
    "name": "cryptography",
    "version": "3.4.8",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "BSD OR Apache License, Version 2.0"
    ],
    "cpes": [],
    "purl": "pkg:pypi/cryptography@3.4.8",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-jm77-qphf-c4w8",
    "dataSource": "https://github.com/advisories/GHSA-jm77-qphf-c4w8",
    "namespace": "github:language:python",
    "severity": "Low",
    "urls": [
     "https://github.com/advisories/GHSA-jm77-qphf-c4w8"
    ],
    "description": "pyca/cryptography's wheels include vulnerable OpenSSL",
    "cvss": [],
    "fix": {
     "versions": [
      "41.0.3"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "cryptography",
       "version": "3.4.8"
      }
     },
     "found": {
      "versionConstraint": ">=0.8,<41.0.3 (python)",
      "vulnerabilityID": "GHSA-jm77-qphf-c4w8"
     }
    }
   ],
   "artifact": {
    "id": "5c06ada74268d17c",
    "name": "cryptography",
    "version": "3.4.8",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "BSD OR Apache License, Version 2.0"
    ],
    "cpes": [],
    "purl": "pkg:pypi/cryptography@3.4.8",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-5cpq-8wj7-hf2v",
    "dataSource": "https://github.com/advisories/GHSA-5cpq-8wj7-hf2v",
    "namespace": "github:language:python",
    "severity": "Low",
    "urls": [
     "https://github.com/advisories/GHSA-5cpq-8wj7-hf2v"
    ],
    "description": "Vulnerable OpenSSL included in cryptography wheels",
    "cvss": [],
    "fix": {
     "versions": [
      "41.0.0"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "cryptography",
       "version": "3.4.8"
      }
     },
     "found": {
      "versionConstraint": ">=0.5,<=40.0.2 (python)",
      "vulnerabilityID": "GHSA-5cpq-8wj7-hf2v"
     }
    }
   ],
   "artifact": {
    "id": "5c06ada74268d17c",
    "name": "cryptography",
    "version": "3.4.8",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "BSD OR Apache License, Version 2.0"
    ],
    "cpes": [],
    "purl": "pkg:pypi/cryptography@3.4.8",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-x7m3-jprg-wc5g",
    "dataSource": "https://github.com/advisories/GHSA-x7m3-jprg-wc5g",
    "namespace": "github:language:python",
    "severity": "Critical",
    "urls": [
     "https://github.com/advisories/GHSA-x7m3-jprg-wc5g"
    ],
    "description": "Gevent allows remote attacker to escalate privileges",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "metrics": {
       "baseScore": 9.8,
       "exploitabilityScore": 3.9,
       "impactScore": 5.9
      },
      "vendorMetadata": {
       "base_severity": "Critical",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "23.9.0"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-41419",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-41419",
     "namespace": "nvd:cpe",
     "severity": "Critical",
     "urls": [
      "https://github.com/gevent/gevent/commit/2f53c851eaf926767fbac62385615efd4886221c",
      "https://github.com/gevent/gevent/issues/1989"
     ],
     "description": "An issue in Gevent before version 23.9.0 allows a remote attacker to escalate privileges via a crafted script to the WSGIServer component.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
       "metrics": {
        "baseScore": 9.8,
        "exploitabilityScore": 3.9,
        "impactScore": 5.9
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "gevent",
       "version": "21.8.0"
      }
     },
     "found": {
      "versionConstraint": "<23.9.0 (python)",
      "vulnerabilityID": "GHSA-x7m3-jprg-wc5g"
     }
    }
   ],
   "artifact": {
    "id": "c3a3a5547752d0e9",
    "name": "gevent",
    "version": "21.8.0",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "MIT"
    ],
    "cpes": [],
    "purl": "pkg:pypi/gevent@21.8.0",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-pfrx-2q88-qq97",
    "dataSource": "https://github.com/advisories/GHSA-pfrx-2q88-qq97",
    "namespace": "github:language:javascript",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-pfrx-2q88-qq97"
    ],
    "description": "Got allows a redirect to a UNIX socket",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
      "metrics": {
       "baseScore": 5.3,
       "exploitabilityScore": 3.9,
       "impactScore": 1.4
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "11.8.5"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2022-33987",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2022-33987",
     "namespace": "nvd:cpe",
     "severity": "Medium",
     "urls": [
      "https://github.com/sindresorhus/got/compare/v12.0.3...v12.1.0",
      "https://github.com/sindresorhus/got/pull/2047",
      "https://github.com/sindresorhus/got/releases/tag/v11.8.5"
     ],
     "description": "The got package before 12.1.0 (also fixed in 11.8.5) for Node.js allows a redirect to a UNIX socket.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "2.0",
       "vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N",
       "metrics": {
        "baseScore": 5,
        "exploitabilityScore": 10,
        "impactScore": 2.9
       },
       "vendorMetadata": {}
      },
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
       "metrics": {
        "baseScore": 5.3,
        "exploitabilityScore": 3.9,
        "impactScore": 1.4
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "javascript-matcher",
     "searchedBy": {
      "language": "javascript",
      "namespace": "github:language:javascript",
      "package": {
       "name": "got",
       "version": "11.8.3"
      }
     },
     "found": {
      "versionConstraint": "<11.8.5 (unknown)",
      "vulnerabilityID": "GHSA-pfrx-2q88-qq97"
     }
    }
   ],
   "artifact": {
    "id": "81901e637ae2c43f",
    "name": "got",
    "version": "11.8.3",
    "type": "npm",
    "locations": [],
    "language": "javascript",
    "licenses": [
     "MIT"
    ],
    "cpes": [],
    "purl": "pkg:npm/got@11.8.3",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-rc47-6667-2j5j",
    "dataSource": "https://github.com/advisories/GHSA-rc47-6667-2j5j",
    "namespace": "github:language:javascript",
    "severity": "High",
    "urls": [
     "https://github.com/advisories/GHSA-rc47-6667-2j5j"
    ],
    "description": "http-cache-semantics vulnerable to Regular Expression Denial of Service",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "metrics": {
       "baseScore": 7.5,
       "exploitabilityScore": 3.9,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "High",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "4.1.1"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2022-25881",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2022-25881",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://github.com/kornelski/http-cache-semantics/blob/master/index.js%23L83",
      "https://security.netapp.com/advisory/ntap-20230622-0008/",
      "https://security.snyk.io/vuln/SNYK-JAVA-ORGWEBJARSNPM-3253332",
      "https://security.snyk.io/vuln/SNYK-JS-HTTPCACHESEMANTICS-3248783"
     ],
     "description": "This affects versions of the package http-cache-semantics before 4.1.1. The issue can be exploited via malicious request header values sent to a server, when that server reads the cache policy from the request using this library.\r\r",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      },
      {
       "source": "report@snyk.io",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
       "metrics": {
        "baseScore": 5.3,
        "exploitabilityScore": 3.9,
        "impactScore": 1.4
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "javascript-matcher",
     "searchedBy": {
      "language": "javascript",
      "namespace": "github:language:javascript",
      "package": {
       "name": "http-cache-semantics",
       "version": "4.1.0"
      }
     },
     "found": {
      "versionConstraint": "<4.1.1 (unknown)",
      "vulnerabilityID": "GHSA-rc47-6667-2j5j"
     }
    }
   ],
   "artifact": {
    "id": "fcf9cae2caedb554",
    "name": "http-cache-semantics",
    "version": "4.1.0",
    "type": "npm",
    "locations": [],
    "language": "javascript",
    "licenses": [
     "BSD-2-Clause"
    ],
    "cpes": [],
    "purl": "pkg:npm/http-cache-semantics@4.1.0",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-jjg7-2v4v-x38h",
    "dataSource": "https://github.com/advisories/GHSA-jjg7-2v4v-x38h",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-jjg7-2v4v-x38h"
    ],
    "description": "Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "metrics": {
       "baseScore": 6.2,
       "exploitabilityScore": 2.5,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "3.7"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "idna",
       "version": "3.3"
      }
     },
     "found": {
      "versionConstraint": "<3.7 (python)",
      "vulnerabilityID": "GHSA-jjg7-2v4v-x38h"
     }
    }
   ],
   "artifact": {
    "id": "abe11c54d846d3fa",
    "name": "idna",
    "version": "3.3",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "BSD-3-Clause"
    ],
    "cpes": [],
    "purl": "pkg:pypi/idna@3.3",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-78xj-cgh5-2h22",
    "dataSource": "https://github.com/advisories/GHSA-78xj-cgh5-2h22",
    "namespace": "github:language:javascript",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-78xj-cgh5-2h22"
    ],
    "description": "NPM IP package incorrectly identifies some private IP addresses as public",
    "cvss": [],
    "fix": {
     "versions": [
      "1.1.9"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-42282",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-42282",
     "namespace": "nvd:cpe",
     "severity": "Critical",
     "urls": [
      "https://cosmosofcyberspace.github.io/npm_ip_cve/npm_ip_cve.html",
      "https://github.com/indutny/node-ip/commit/6a3ada9b471b09d5f0f5be264911ab564bf67894",
      "https://huntr.com/bounties/bfc3b23f-ddc0-4ee7-afab-223b07115ed3/",
      "https://security.netapp.com/advisory/ntap-20240315-0008/"
     ],
     "description": "The ip package before 1.1.9 for Node.js might allow SSRF because some IP addresses (such as 0x7f.1) are improperly categorized as globally routable via isPublic.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
       "metrics": {
        "baseScore": 9.8,
        "exploitabilityScore": 3.9,
        "impactScore": 5.9
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "javascript-matcher",
     "searchedBy": {
      "language": "javascript",
      "namespace": "github:language:javascript",
      "package": {
       "name": "ip",
       "version": "1.1.5"
      }
     },
     "found": {
      "versionConstraint": "<1.1.9 (unknown)",
      "vulnerabilityID": "GHSA-78xj-cgh5-2h22"
     }
    }
   ],
   "artifact": {
    "id": "d61e89d9574e97c4",
    "name": "ip",
    "version": "1.1.5",
    "type": "npm",
    "locations": [],
    "language": "javascript",
    "licenses": [
     "MIT"
    ],
    "cpes": [],
    "purl": "pkg:npm/ip@1.1.5",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-h5c8-rqwp-cp95",
    "dataSource": "https://github.com/advisories/GHSA-h5c8-rqwp-cp95",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-h5c8-rqwp-cp95"
    ],
    "description": "Jinja vulnerable to HTML attribute injection when passing user input as keys to xmlattr filter",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N",
      "metrics": {
       "baseScore": 5.4,
       "exploitabilityScore": 2.8,
       "impactScore": 2.5
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "3.1.3"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2024-22195",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-22195",
     "namespace": "nvd:cpe",
     "severity": "Medium",
     "urls": [
      "https://github.com/pallets/jinja/releases/tag/3.1.3",
      "https://github.com/pallets/jinja/security/advisories/GHSA-h5c8-rqwp-cp95",
      "https://lists.debian.org/debian-lts-announce/2024/01/msg00010.html",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5XCWZD464AJJJUBOO7CMPXQ4ROBC6JX2/",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DELCVUUYX75I5K4Q5WMJG4MUZJA6VAIP/",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O7YWRBX6JQCWC2XXCTZ55C7DPMGICCN3/"
     ],
     "description": "Jinja is an extensible templating engine. Special placeholders in the template allow writing code similar to Python syntax. It is possible to inject arbitrary HTML attributes into the rendered HTML template, potentially leading to Cross-Site Scripting (XSS). The Jinja `xmlattr` filter can be abused to inject arbitrary HTML attribute keys and values, bypassing the auto escaping mechanism and potentially leading to XSS. It may also be possible to bypass attribute validation checks if they are blacklist-based.\n",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
       "metrics": {
        "baseScore": 6.1,
        "exploitabilityScore": 2.8,
        "impactScore": 2.7
       },
       "vendorMetadata": {}
      },
      {
       "source": "security-advisories@github.com",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N",
       "metrics": {
        "baseScore": 5.4,
        "exploitabilityScore": 2.8,
        "impactScore": 2.5
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "jinja2",
       "version": "3.0.3"
      }
     },
     "found": {
      "versionConstraint": "<3.1.3 (python)",
      "vulnerabilityID": "GHSA-h5c8-rqwp-cp95"
     }
    }
   ],
   "artifact": {
    "id": "82224e4b19d11204",
    "name": "jinja2",
    "version": "3.0.3",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "BSD-3-Clause"
    ],
    "cpes": [],
    "purl": "pkg:pypi/jinja2@3.0.3",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-wrxv-2j5q-m38w",
    "dataSource": "https://github.com/advisories/GHSA-wrxv-2j5q-m38w",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-wrxv-2j5q-m38w"
    ],
    "description": "lxml NULL Pointer Dereference allows attackers to cause a denial of service",
    "cvss": [
     {
      "version": "3.0",
      "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
      "metrics": {
       "baseScore": 5.3,
       "exploitabilityScore": 3.9,
       "impactScore": 1.4
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "4.9.1"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2022-2309",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2022-2309",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://github.com/lxml/lxml/commit/86368e9cf70a0ad23cccd5ee32de847149af0c6f",
      "https://huntr.dev/bounties/8264e74f-edda-4c40-9956-49de635105ba",
      "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HGYC6L7ENH5VEGN3YWFBYMGKX6WNS7HZ/",
      "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/URHHSIBTPTALXMECRLAC2EVDNAFSR5NO/",
      "https://security.gentoo.org/glsa/202208-06",
      "https://security.netapp.com/advisory/ntap-20220915-0006/"
     ],
     "description": "NULL Pointer Dereference allows attackers to cause a denial of service (or application crash). This only applies when lxml is used together with libxml2 2.9.10 through 2.9.14. libxml2 2.9.9 and earlier are not affected. It allows triggering crashes through forged input data, given a vulnerable code sequence in the application. The vulnerability is caused by the iterwalk function (also used by the canonicalize function). Such code shouldn't be in wide-spread use, given that parsing + iterwalk would usually be replaced with the more efficient iterparse function. However, an XML converter that serialises to C14N would also be vulnerable, for example, and there are legitimate use cases for this code sequence. If untrusted input is received (also remotely) and processed via iterwalk function, a crash can be triggered.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "2.0",
       "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
       "metrics": {
        "baseScore": 5,
        "exploitabilityScore": 10,
        "impactScore": 2.9
       },
       "vendorMetadata": {}
      },
      {
       "source": "security@huntr.dev",
       "type": "Secondary",
       "version": "3.0",
       "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
       "metrics": {
        "baseScore": 5.3,
        "exploitabilityScore": 3.9,
        "impactScore": 1.4
       },
       "vendorMetadata": {}
      },
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "lxml",
       "version": "4.8.0"
      }
     },
     "found": {
      "versionConstraint": "<4.9.1 (python)",
      "vulnerabilityID": "GHSA-wrxv-2j5q-m38w"
     }
    }
   ],
   "artifact": {
    "id": "d12d5ae25d372472",
    "name": "lxml",
    "version": "4.8.0",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "BSD"
    ],
    "cpes": [],
    "purl": "pkg:pypi/lxml@4.8.0",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-hj9c-8jmm-8c52",
    "dataSource": "https://github.com/advisories/GHSA-hj9c-8jmm-8c52",
    "namespace": "github:language:javascript",
    "severity": "High",
    "urls": [
     "https://github.com/advisories/GHSA-hj9c-8jmm-8c52"
    ],
    "description": "Packing does not respect root-level ignore files in workspaces",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
      "metrics": {
       "baseScore": 7.5,
       "exploitabilityScore": 3.9,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "High",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "8.11.0"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2022-29244",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2022-29244",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://github.com/nodejs/node/pull/43210",
      "https://github.com/nodejs/node/releases/tag/v16.15.1",
      "https://github.com/nodejs/node/releases/tag/v17.9.1",
      "https://github.com/nodejs/node/releases/tag/v18.3.0",
      "https://github.com/npm/cli/releases/tag/v8.11.0",
      "https://github.com/npm/cli/security/advisories/GHSA-hj9c-8jmm-8c52",
      "https://github.com/npm/cli/tree/latest/workspaces/libnpmpack",
      "https://github.com/npm/cli/tree/latest/workspaces/libnpmpublish",
      "https://github.com/npm/npm-packlist",
      "https://security.netapp.com/advisory/ntap-20220722-0007/"
     ],
     "description": "npm pack ignores root-level .gitignore and .npmignore file exclusion directives when run in a workspace or with a workspace flag (ie. `--workspaces`, `--workspace=<name>`). Anyone who has run `npm pack` or `npm publish` inside a workspace, as of v7.9.0 and v7.13.0 respectively, may be affected and have published files into the npm registry they did not intend to include. Users should upgrade to the latest, patched version of npm v8.11.0, run: npm i -g npm@latest . Node.js versions v16.15.1, v17.19.1, and v18.3.0 include the patched v8.11.0 version of npm.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "2.0",
       "vector": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
       "metrics": {
        "baseScore": 5,
        "exploitabilityScore": 10,
        "impactScore": 2.9
       },
       "vendorMetadata": {}
      },
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "javascript-matcher",
     "searchedBy": {
      "language": "javascript",
      "namespace": "github:language:javascript",
      "package": {
       "name": "npm",
       "version": "8.5.1"
      }
     },
     "found": {
      "versionConstraint": ">=7.9.0,<8.11.0 (unknown)",
      "vulnerabilityID": "GHSA-hj9c-8jmm-8c52"
     }
    }
   ],
   "artifact": {
    "id": "d2b03371dae259be",
    "name": "npm",
    "version": "8.5.1",
    "type": "npm",
    "locations": [],
    "language": "javascript",
    "licenses": [
     "Artistic-2.0"
    ],
    "cpes": [],
    "purl": "pkg:npm/npm@8.5.1",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-m2vv-5vj5-2hm7",
    "dataSource": "https://github.com/advisories/GHSA-m2vv-5vj5-2hm7",
    "namespace": "github:language:python",
    "severity": "High",
    "urls": [
     "https://github.com/advisories/GHSA-m2vv-5vj5-2hm7"
    ],
    "description": "Pillow vulnerable to Data Amplification attack.",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "metrics": {
       "baseScore": 7.5,
       "exploitabilityScore": 3.9,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "High",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "9.2.0"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2022-45198",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2022-45198",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://bugs.gentoo.org/855683",
      "https://cwe.mitre.org/data/definitions/409.html",
      "https://github.com/python-pillow/Pillow/commit/11918eac0628ec8ac0812670d9838361ead2d6a4",
      "https://github.com/python-pillow/Pillow/pull/6402",
      "https://github.com/python-pillow/Pillow/releases/tag/9.2.0",
      "https://security.gentoo.org/glsa/202211-10"
     ],
     "description": "Pillow before 9.2.0 performs Improper Handling of Highly Compressed GIF Data (Data Amplification).",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "pillow",
       "version": "9.0.1"
      }
     },
     "found": {
      "versionConstraint": "<9.2.0 (python)",
      "vulnerabilityID": "GHSA-m2vv-5vj5-2hm7"
     }
    }
   ],
   "artifact": {
    "id": "c25834028c6396b4",
    "name": "pillow",
    "version": "9.0.1",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "HPND"
    ],
    "cpes": [],
    "purl": "pkg:pypi/pillow@9.0.1",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-j7hp-h8jx-5ppr",
    "dataSource": "https://github.com/advisories/GHSA-j7hp-h8jx-5ppr",
    "namespace": "github:language:python",
    "severity": "High",
    "urls": [
     "https://github.com/advisories/GHSA-j7hp-h8jx-5ppr"
    ],
    "description": "libwebp: OOB write in BuildHuffmanTable",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "metrics": {
       "baseScore": 8.8,
       "exploitabilityScore": 2.8,
       "impactScore": 5.9
      },
      "vendorMetadata": {
       "base_severity": "High",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "10.0.1"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-4863",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-4863",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "http://www.openwall.com/lists/oss-security/2023/09/21/4",
      "http://www.openwall.com/lists/oss-security/2023/09/22/1",
      "http://www.openwall.com/lists/oss-security/2023/09/22/3",
      "http://www.openwall.com/lists/oss-security/2023/09/22/4",
      "http://www.openwall.com/lists/oss-security/2023/09/22/5",
      "http://www.openwall.com/lists/oss-security/2023/09/22/6",
      "http://www.openwall.com/lists/oss-security/2023/09/22/7",
      "http://www.openwall.com/lists/oss-security/2023/09/22/8",
      "http://www.openwall.com/lists/oss-security/2023/09/26/1",
      "http://www.openwall.com/lists/oss-security/2023/09/26/7",
      "http://www.openwall.com/lists/oss-security/2023/09/28/1",
      "http://www.openwall.com/lists/oss-security/2023/09/28/2",
      "http://www.openwall.com/lists/oss-security/2023/09/28/4",
      "https://adamcaudill.com/2023/09/14/whose-cve-is-it-anyway/",
      "https://blog.isosceles.com/the-webp-0day/",
      "https://bugzilla.suse.com/show_bug.cgi?id=1215231",
      "https://chromereleases.googleblog.com/2023/09/stable-channel-update-for-desktop_11.html",
      "https://crbug.com/1479274",
      "https://en.bandisoft.com/honeyview/history/",
      "https://github.com/webmproject/libwebp/commit/902bc9190331343b2017211debcec8d2ab87e17a",
      "https://github.com/webmproject/libwebp/releases/tag/v1.3.2",
      "https://lists.debian.org/debian-lts-announce/2023/09/msg00015.html",
      "https://lists.debian.org/debian-lts-announce/2023/09/msg00016.html",
      "https://lists.debian.org/debian-lts-announce/2023/09/msg00017.html",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6T655QF7CQ3DYAMPFV7IECQYGDEUIVVT/",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FYYKLG6CRGEDTNRBSU26EEWAO6D6U645/",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KUQ7CTX3W372X3UY56VVNAHCH6H2F4X3/",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OZDGWWMJREPAGKWCJKSCM4WYLANSKIFX/",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PYZV7TMKF4QHZ54SFJX54BDN52VHGGCX/",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WHOLML7N2G5KCAZXFWC5IDFFHSQS5SDB/",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WTRUIS3564P7ZLM2S2IH4Y4KZ327LI4I/",
      "https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-4863",
      "https://news.ycombinator.com/item?id=37478403",
      "https://security-tracker.debian.org/tracker/CVE-2023-4863",
      "https://security.gentoo.org/glsa/202309-05",
      "https://security.gentoo.org/glsa/202401-10",
      "https://security.netapp.com/advisory/ntap-20230929-0011/",
      "https://sethmlarson.dev/security-developer-in-residence-weekly-report-16",
      "https://stackdiary.com/critical-vulnerability-in-webp-codec-cve-2023-4863/",
      "https://www.bentley.com/advisories/be-2023-0001/",
      "https://www.bleepingcomputer.com/news/google/google-fixes-another-chrome-zero-day-bug-exploited-in-attacks/",
      "https://www.debian.org/security/2023/dsa-5496",
      "https://www.debian.org/security/2023/dsa-5497",
      "https://www.debian.org/security/2023/dsa-5498",
      "https://www.mozilla.org/en-US/security/advisories/mfsa2023-40/"
     ],
     "description": "Heap buffer overflow in libwebp in Google Chrome prior to 116.0.5845.187 and libwebp 1.3.2 allowed a remote attacker to perform an out of bounds memory write via a crafted HTML page. (Chromium security severity: Critical)",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
       "metrics": {
        "baseScore": 8.8,
        "exploitabilityScore": 2.8,
        "impactScore": 5.9
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "pillow",
       "version": "9.0.1"
      }
     },
     "found": {
      "versionConstraint": "<10.0.1 (python)",
      "vulnerabilityID": "GHSA-j7hp-h8jx-5ppr"
     }
    }
   ],
   "artifact": {
    "id": "c25834028c6396b4",
    "name": "pillow",
    "version": "9.0.1",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "HPND"
    ],
    "cpes": [],
    "purl": "pkg:pypi/pillow@9.0.1",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-8ghj-p4vj-mr35",
    "dataSource": "https://github.com/advisories/GHSA-8ghj-p4vj-mr35",
    "namespace": "github:language:python",
    "severity": "High",
    "urls": [
     "https://github.com/advisories/GHSA-8ghj-p4vj-mr35"
    ],
    "description": "Pillow Denial of Service vulnerability",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "metrics": {
       "baseScore": 7.5,
       "exploitabilityScore": 3.9,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "High",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "10.0.0"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-44271",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-44271",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://devhub.checkmarx.com/cve-details/CVE-2023-44271/",
      "https://github.com/python-pillow/Pillow/commit/1fe1bb49c452b0318cad12ea9d97c3bef188e9a7",
      "https://github.com/python-pillow/Pillow/pull/7244",
      "https://lists.debian.org/debian-lts-announce/2024/03/msg00021.html",
      "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N2JOEDUJDQLCUII2LQYZYSM7RJL2I3P4/"
     ],
     "description": "An issue was discovered in Pillow before 10.0.0. It is a Denial of Service that uncontrollably allocates memory to process a given task, potentially causing a service to crash by having it run out of memory. This occurs for truetype in ImageFont when textlength in an ImageDraw instance operates on a long text argument.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "pillow",
       "version": "9.0.1"
      }
     },
     "found": {
      "versionConstraint": ">=0,<10.0.0 (python)",
      "vulnerabilityID": "GHSA-8ghj-p4vj-mr35"
     }
    }
   ],
   "artifact": {
    "id": "c25834028c6396b4",
    "name": "pillow",
    "version": "9.0.1",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "HPND"
    ],
    "cpes": [],
    "purl": "pkg:pypi/pillow@9.0.1",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-56pw-mpj4-fxww",
    "dataSource": "https://github.com/advisories/GHSA-56pw-mpj4-fxww",
    "namespace": "github:language:python",
    "severity": "High",
    "urls": [
     "https://github.com/advisories/GHSA-56pw-mpj4-fxww"
    ],
    "description": "Bundled libwebp in Pillow vulnerable",
    "cvss": [],
    "fix": {
     "versions": [
      "10.0.1"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "pillow",
       "version": "9.0.1"
      }
     },
     "found": {
      "versionConstraint": "<10.0.1 (python)",
      "vulnerabilityID": "GHSA-56pw-mpj4-fxww"
     }
    }
   ],
   "artifact": {
    "id": "c25834028c6396b4",
    "name": "pillow",
    "version": "9.0.1",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "HPND"
    ],
    "cpes": [],
    "purl": "pkg:pypi/pillow@9.0.1",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-3f63-hfp8-52jq",
    "dataSource": "https://github.com/advisories/GHSA-3f63-hfp8-52jq",
    "namespace": "github:language:python",
    "severity": "High",
    "urls": [
     "https://github.com/advisories/GHSA-3f63-hfp8-52jq"
    ],
    "description": "Arbitrary Code Execution in Pillow",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "metrics": {
       "baseScore": 8.1,
       "exploitabilityScore": 2.2,
       "impactScore": 5.9
      },
      "vendorMetadata": {
       "base_severity": "High",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "10.2.0"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-50447",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-50447",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "http://www.openwall.com/lists/oss-security/2024/01/20/1",
      "https://devhub.checkmarx.com/cve-details/CVE-2023-50447/",
      "https://duartecsantos.github.io/2024-01-02-CVE-2023-50447/",
      "https://github.com/python-pillow/Pillow/releases",
      "https://lists.debian.org/debian-lts-announce/2024/01/msg00019.html"
     ],
     "description": "Pillow through 10.1.0 allows PIL.ImageMath.eval Arbitrary Code Execution via the environment parameter, a different vulnerability than CVE-2022-22817 (which was about the expression parameter).",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
       "metrics": {
        "baseScore": 8.1,
        "exploitabilityScore": 2.2,
        "impactScore": 5.9
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "pillow",
       "version": "9.0.1"
      }
     },
     "found": {
      "versionConstraint": "<10.2.0 (python)",
      "vulnerabilityID": "GHSA-3f63-hfp8-52jq"
     }
    }
   ],
   "artifact": {
    "id": "c25834028c6396b4",
    "name": "pillow",
    "version": "9.0.1",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "HPND"
    ],
    "cpes": [],
    "purl": "pkg:pypi/pillow@9.0.1",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-44wm-f244-xhp3",
    "dataSource": "https://github.com/advisories/GHSA-44wm-f244-xhp3",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-44wm-f244-xhp3"
    ],
    "description": "Pillow buffer overflow vulnerability",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:H/I:H/A:H",
      "metrics": {
       "baseScore": 6.7,
       "exploitabilityScore": 0.8,
       "impactScore": 5.9
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "10.3.0"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2024-28219",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-28219",
     "namespace": "nvd:cpe",
     "severity": "Medium",
     "urls": [
      "https://lists.debian.org/debian-lts-announce/2024/04/msg00008.html",
      "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4XLPUT3VK4GQ6EVY525TT2QNUIXNRU5M/",
      "https://pillow.readthedocs.io/en/stable/releasenotes/10.3.0.html#security"
     ],
     "description": "In _imagingcms.c in Pillow before 10.3.0, a buffer overflow exists because strcpy is used instead of strncpy.",
     "cvss": [
      {
       "source": "cve@mitre.org",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:H/I:H/A:H",
       "metrics": {
        "baseScore": 6.7,
        "exploitabilityScore": 0.8,
        "impactScore": 5.9
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "pillow",
       "version": "9.0.1"
      }
     },
     "found": {
      "versionConstraint": "<10.3.0 (python)",
      "vulnerabilityID": "GHSA-44wm-f244-xhp3"
     }
    }
   ],
   "artifact": {
    "id": "c25834028c6396b4",
    "name": "pillow",
    "version": "9.0.1",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "HPND"
    ],
    "cpes": [],
    "purl": "pkg:pypi/pillow@9.0.1",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-mq26-g339-26xf",
    "dataSource": "https://github.com/advisories/GHSA-mq26-g339-26xf",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-mq26-g339-26xf"
    ],
    "description": "Command Injection in pip when used with Mercurial",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
      "metrics": {
       "baseScore": 5.5,
       "exploitabilityScore": 1.8,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "23.3"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-5752",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-5752",
     "namespace": "nvd:cpe",
     "severity": "Low",
     "urls": [
      "https://github.com/pypa/pip/pull/12306",
      "https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/"
     ],
     "description": "When installing a package from a Mercurial VCS URL  (ie \"pip install \nhg+...\") with pip prior to v23.3, the specified Mercurial revision could\n be used to inject arbitrary configuration options to the \"hg clone\" \ncall (ie \"--config\"). Controlling the Mercurial configuration can modify\n how and which repository is installed. This vulnerability does not \naffect users who aren't installing from Mercurial.\n",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
       "metrics": {
        "baseScore": 3.3,
        "exploitabilityScore": 1.8,
        "impactScore": 1.4
       },
       "vendorMetadata": {}
      },
      {
       "source": "cna@python.org",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
       "metrics": {
        "baseScore": 5.5,
        "exploitabilityScore": 1.8,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "pip",
       "version": "22.0.2"
      }
     },
     "found": {
      "versionConstraint": "<23.3 (python)",
      "vulnerabilityID": "GHSA-mq26-g339-26xf"
     }
    }
   ],
   "artifact": {
    "id": "243dc77abf631bd2",
    "name": "pip",
    "version": "22.0.2",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "MIT"
    ],
    "cpes": [],
    "purl": "pkg:pypi/pip@22.0.2",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-xcjx-m2pj-8g79",
    "dataSource": "https://github.com/advisories/GHSA-xcjx-m2pj-8g79",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-xcjx-m2pj-8g79"
    ],
    "description": "Manipulated inline images can cause Infinite Loop in PyPDF2",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "metrics": {
       "baseScore": 6.2,
       "exploitabilityScore": 2.5,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "1.27.5"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2022-24859",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2022-24859",
     "namespace": "nvd:cpe",
     "severity": "Medium",
     "urls": [
      "https://github.com/py-pdf/PyPDF2/issues/329",
      "https://github.com/py-pdf/PyPDF2/pull/740",
      "https://github.com/py-pdf/PyPDF2/releases/tag/1.27.5",
      "https://github.com/py-pdf/PyPDF2/security/advisories/GHSA-xcjx-m2pj-8g79",
      "https://lists.debian.org/debian-lts-announce/2022/06/msg00001.html",
      "https://lists.debian.org/debian-lts-announce/2023/06/msg00013.html"
     ],
     "description": "PyPDF2 is an open source python PDF library capable of splitting, merging, cropping, and transforming the pages of PDF files. In versions prior to 1.27.5 an attacker who uses this vulnerability can craft a PDF which leads to an infinite loop if the PyPDF2 if the code attempts to get the content stream. The reason is that the last while-loop in `ContentStream._readInlineImage` only terminates when it finds the `EI` token, but never actually checks if the stream has already ended. This issue has been resolved in version `1.27.5`. Users unable to upgrade should validate and PDFs prior to iterating over their content stream.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "2.0",
       "vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
       "metrics": {
        "baseScore": 4.3,
        "exploitabilityScore": 8.6,
        "impactScore": 2.9
       },
       "vendorMetadata": {}
      },
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 5.5,
        "exploitabilityScore": 1.8,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      },
      {
       "source": "security-advisories@github.com",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 6.2,
        "exploitabilityScore": 2.5,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "pypdf2",
       "version": "1.26.0"
      }
     },
     "found": {
      "versionConstraint": "<1.27.5 (python)",
      "vulnerabilityID": "GHSA-xcjx-m2pj-8g79"
     }
    }
   ],
   "artifact": {
    "id": "dc1e08b96eabb2ff",
    "name": "pypdf2",
    "version": "1.26.0",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "UNKNOWN"
    ],
    "cpes": [],
    "purl": "pkg:pypi/pypdf2@1.26.0",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-jrm6-h9cq-8gqw",
    "dataSource": "https://github.com/advisories/GHSA-jrm6-h9cq-8gqw",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-jrm6-h9cq-8gqw"
    ],
    "description": "PyPDF2 quadratic runtime with malformed PDF missing xref marker",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "metrics": {
       "baseScore": 6.2,
       "exploitabilityScore": 2.5,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "1.27.9"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-36810",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-36810",
     "namespace": "nvd:cpe",
     "severity": "Medium",
     "urls": [
      "https://github.com/py-pdf/pypdf/issues/582",
      "https://github.com/py-pdf/pypdf/pull/808",
      "https://github.com/py-pdf/pypdf/security/advisories/GHSA-jrm6-h9cq-8gqw",
      "https://lists.debian.org/debian-lts-announce/2023/07/msg00019.html"
     ],
     "description": "pypdf is a pure-python PDF library capable of splitting, merging, cropping, and transforming the pages of PDF files. An attacker who uses this vulnerability can craft a PDF which leads to unexpected long runtime. This quadratic runtime blocks the current process and can utilize a single core of the CPU by 100%. It does not affect memory usage. This issue has been addressed in PR 808 and versions from 1.27.9 include this fix. Users are advised to upgrade. There are no known workarounds for this vulnerability.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 6.5,
        "exploitabilityScore": 2.8,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      },
      {
       "source": "security-advisories@github.com",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 6.2,
        "exploitabilityScore": 2.5,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "pypdf2",
       "version": "1.26.0"
      }
     },
     "found": {
      "versionConstraint": "<=1.27.8 (python)",
      "vulnerabilityID": "GHSA-jrm6-h9cq-8gqw"
     }
    }
   ],
   "artifact": {
    "id": "dc1e08b96eabb2ff",
    "name": "pypdf2",
    "version": "1.26.0",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "UNKNOWN"
    ],
    "cpes": [],
    "purl": "pkg:pypi/pypdf2@1.26.0",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-r8wq-qrxc-hmcm",
    "dataSource": "https://github.com/advisories/GHSA-r8wq-qrxc-hmcm",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-r8wq-qrxc-hmcm"
    ],
    "description": "ReDoS in LDAP schema parser",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
      "metrics": {
       "baseScore": 6.5,
       "exploitabilityScore": 2.8,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "3.4.0"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "python-ldap",
       "version": "3.2.0"
      }
     },
     "found": {
      "versionConstraint": "<3.4.0 (python)",
      "vulnerabilityID": "GHSA-r8wq-qrxc-hmcm"
     }
    }
   ],
   "artifact": {
    "id": "c981e72233e0a8b6",
    "name": "python-ldap",
    "version": "3.2.0",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "Python style"
    ],
    "cpes": [],
    "purl": "pkg:pypi/python-ldap@3.2.0",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-qfr5-wjpw-q4c4",
    "dataSource": "https://github.com/advisories/GHSA-qfr5-wjpw-q4c4",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-qfr5-wjpw-q4c4"
    ],
    "description": "Denial of Service in python-ldap",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
      "metrics": {
       "baseScore": 6.5,
       "exploitabilityScore": 2.8,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "3.4.0"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2021-46823",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2021-46823",
     "namespace": "nvd:cpe",
     "severity": "Medium",
     "urls": [
      "https://exchange.xforce.ibmcloud.com/vulnerabilities/221507",
      "https://github.com/python-ldap/python-ldap/security/advisories/GHSA-r8wq-qrxc-hmcm"
     ],
     "description": "python-ldap before 3.4.0 is vulnerable to a denial of service when ldap.schema is used for untrusted schema definitions, because of a regular expression denial of service (ReDoS) flaw in the LDAP schema parser. By sending crafted regex input, a remote authenticated attacker could exploit this vulnerability to cause a denial of service condition.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "2.0",
       "vector": "AV:N/AC:L/Au:S/C:N/I:N/A:P",
       "metrics": {
        "baseScore": 4,
        "exploitabilityScore": 8,
        "impactScore": 2.9
       },
       "vendorMetadata": {}
      },
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 6.5,
        "exploitabilityScore": 2.8,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "python-ldap",
       "version": "3.2.0"
      }
     },
     "found": {
      "versionConstraint": "<3.4.0 (python)",
      "vulnerabilityID": "GHSA-qfr5-wjpw-q4c4"
     }
    }
   ],
   "artifact": {
    "id": "c981e72233e0a8b6",
    "name": "python-ldap",
    "version": "3.2.0",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "Python style"
    ],
    "cpes": [],
    "purl": "pkg:pypi/python-ldap@3.2.0",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-9q9m-c65c-37pq",
    "dataSource": "https://github.com/advisories/GHSA-9q9m-c65c-37pq",
    "namespace": "github:language:python",
    "severity": "High",
    "urls": [
     "https://github.com/advisories/GHSA-9q9m-c65c-37pq"
    ],
    "description": "Reportlab vulnerable to remote code execution",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "metrics": {
       "baseScore": 7.8,
       "exploitabilityScore": 1.8,
       "impactScore": 5.9
      },
      "vendorMetadata": {
       "base_severity": "High",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "3.6.13"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-33733",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-33733",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://github.com/c53elyas/CVE-2023-33733",
      "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/36WOY22ECJCPOXHVTNCHEWOQLL7JSWP4/",
      "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6ALE727IRACYBTTOFIFG57RS4OA2SHIJ/"
     ],
     "description": "Reportlab up to v3.6.12 allows attackers to execute arbitrary code via supplying a crafted PDF file.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
       "metrics": {
        "baseScore": 7.8,
        "exploitabilityScore": 1.8,
        "impactScore": 5.9
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "reportlab",
       "version": "3.6.8"
      }
     },
     "found": {
      "versionConstraint": "<=3.6.12 (python)",
      "vulnerabilityID": "GHSA-9q9m-c65c-37pq"
     }
    }
   ],
   "artifact": {
    "id": "97479aee9824a25a",
    "name": "reportlab",
    "version": "3.6.8",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "BSD license (see license.txt for details), Copyright (c) 2000-2018, ReportLab Inc."
    ],
    "cpes": [],
    "purl": "pkg:pypi/reportlab@3.6.8",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-j8r2-6x86-q33q",
    "dataSource": "https://github.com/advisories/GHSA-j8r2-6x86-q33q",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-j8r2-6x86-q33q"
    ],
    "description": "Unintended leak of Proxy-Authorization header in requests",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
      "metrics": {
       "baseScore": 6.1,
       "exploitabilityScore": 1.6,
       "impactScore": 4
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "2.31.0"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-32681",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-32681",
     "namespace": "nvd:cpe",
     "severity": "Medium",
     "urls": [
      "https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5",
      "https://github.com/psf/requests/releases/tag/v2.31.0",
      "https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q",
      "https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y/",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ/",
      "https://security.gentoo.org/glsa/202309-08"
     ],
     "description": "Requests is a HTTP library. Since Requests 2.3.0, Requests has been leaking Proxy-Authorization headers to destination servers when redirected to an HTTPS endpoint. This is a product of how we use `rebuild_proxies` to reattach the `Proxy-Authorization` header to requests. For HTTP connections sent through the tunnel, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into the tunneled request. This results in Requests forwarding proxy credentials to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate sensitive information. This issue has been patched in version 2.31.0.\n\n",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
       "metrics": {
        "baseScore": 6.1,
        "exploitabilityScore": 1.6,
        "impactScore": 4
       },
       "vendorMetadata": {}
      },
      {
       "source": "security-advisories@github.com",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
       "metrics": {
        "baseScore": 6.1,
        "exploitabilityScore": 1.6,
        "impactScore": 4
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "requests",
       "version": "2.25.1"
      }
     },
     "found": {
      "versionConstraint": ">=2.3.0,<2.31.0 (python)",
      "vulnerabilityID": "GHSA-j8r2-6x86-q33q"
     }
    }
   ],
   "artifact": {
    "id": "de6a5cea9ce39f6f",
    "name": "requests",
    "version": "2.25.1",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "Apache 2.0"
    ],
    "cpes": [],
    "purl": "pkg:pypi/requests@2.25.1",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-c2qf-rxjj-qqgw",
    "dataSource": "https://github.com/advisories/GHSA-c2qf-rxjj-qqgw",
    "namespace": "github:language:javascript",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-c2qf-rxjj-qqgw"
    ],
    "description": "semver vulnerable to Regular Expression Denial of Service",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
      "metrics": {
       "baseScore": 5.3,
       "exploitabilityScore": 3.9,
       "impactScore": 1.4
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "7.5.2"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2022-25883",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2022-25883",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://github.com/npm/node-semver/blob/main/classes/range.js%23L97-L104",
      "https://github.com/npm/node-semver/blob/main/internal/re.js%23L138",
      "https://github.com/npm/node-semver/blob/main/internal/re.js%23L160",
      "https://github.com/npm/node-semver/commit/717534ee353682f3bcf33e60a8af4292626d4441",
      "https://github.com/npm/node-semver/pull/564",
      "https://security.snyk.io/vuln/SNYK-JS-SEMVER-3247795"
     ],
     "description": "Versions of the package semver before 7.5.2 are vulnerable to Regular Expression Denial of Service (ReDoS) via the function new Range, when untrusted user data is provided as a range.\r\r\r",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      },
      {
       "source": "report@snyk.io",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
       "metrics": {
        "baseScore": 5.3,
        "exploitabilityScore": 3.9,
        "impactScore": 1.4
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "javascript-matcher",
     "searchedBy": {
      "language": "javascript",
      "namespace": "github:language:javascript",
      "package": {
       "name": "semver",
       "version": "7.3.5"
      }
     },
     "found": {
      "versionConstraint": ">=7.0.0,<7.5.2 (unknown)",
      "vulnerabilityID": "GHSA-c2qf-rxjj-qqgw"
     }
    }
   ],
   "artifact": {
    "id": "94ef965d0140a2ea",
    "name": "semver",
    "version": "7.3.5",
    "type": "npm",
    "locations": [],
    "language": "javascript",
    "licenses": [
     "ISC"
    ],
    "cpes": [],
    "purl": "pkg:npm/semver@7.3.5",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-r9hx-vwmv-q579",
    "dataSource": "https://github.com/advisories/GHSA-r9hx-vwmv-q579",
    "namespace": "github:language:python",
    "severity": "High",
    "urls": [
     "https://github.com/advisories/GHSA-r9hx-vwmv-q579"
    ],
    "description": "pypa/setuptools vulnerable to Regular Expression Denial of Service (ReDoS)",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "metrics": {
       "baseScore": 7.5,
       "exploitabilityScore": 3.9,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "High",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "65.5.1"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2022-40897",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2022-40897",
     "namespace": "nvd:cpe",
     "severity": "Medium",
     "urls": [
      "https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200",
      "https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be",
      "https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1",
      "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/",
      "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/",
      "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
      "https://pyup.io/vulnerabilities/CVE-2022-40897/52495/",
      "https://security.netapp.com/advisory/ntap-20230214-0001/"
     ],
     "description": "Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 5.9,
        "exploitabilityScore": 2.2,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "setuptools",
       "version": "59.6.0"
      }
     },
     "found": {
      "versionConstraint": "<65.5.1 (python)",
      "vulnerabilityID": "GHSA-r9hx-vwmv-q579"
     }
    }
   ],
   "artifact": {
    "id": "e5073ead1a17f923",
    "name": "setuptools",
    "version": "59.6.0",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "UNKNOWN"
    ],
    "cpes": [],
    "purl": "pkg:pypi/setuptools@59.6.0",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-f5x3-32g6-xq36",
    "dataSource": "https://github.com/advisories/GHSA-f5x3-32g6-xq36",
    "namespace": "github:language:javascript",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-f5x3-32g6-xq36"
    ],
    "description": "Denial of service while parsing a tar file due to lack of folders count validation",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
      "metrics": {
       "baseScore": 6.5,
       "exploitabilityScore": 2.8,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "6.2.1"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2024-28863",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2024-28863",
     "namespace": "nvd:cpe",
     "severity": "Medium",
     "urls": [
      "https://github.com/isaacs/node-tar/commit/fe8cd57da5686f8695415414bda49206a545f7f7",
      "https://github.com/isaacs/node-tar/security/advisories/GHSA-f5x3-32g6-xq36"
     ],
     "description": "node-tar is a Tar for Node.js. node-tar prior to version 6.2.1 has no limit on the number of sub-folders created in the folder creation process. An attacker who generates a large number of sub-folders can consume memory on the system running node-tar and even crash the Node.js client within few seconds of running it using a path with too many sub-folders inside. Version 6.2.1 fixes this issue by preventing extraction in excessively deep sub-folders.",
     "cvss": [
      {
       "source": "security-advisories@github.com",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 6.5,
        "exploitabilityScore": 2.8,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "javascript-matcher",
     "searchedBy": {
      "language": "javascript",
      "namespace": "github:language:javascript",
      "package": {
       "name": "tar",
       "version": "6.1.11"
      }
     },
     "found": {
      "versionConstraint": "<6.2.1 (unknown)",
      "vulnerabilityID": "GHSA-f5x3-32g6-xq36"
     }
    }
   ],
   "artifact": {
    "id": "772825200a804f25",
    "name": "tar",
    "version": "6.1.11",
    "type": "npm",
    "locations": [],
    "language": "javascript",
    "licenses": [
     "ISC"
    ],
    "cpes": [],
    "purl": "pkg:npm/tar@6.1.11",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-v845-jxx5-vc9f",
    "dataSource": "https://github.com/advisories/GHSA-v845-jxx5-vc9f",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-v845-jxx5-vc9f"
    ],
    "description": "`Cookie` HTTP header isn't stripped on cross-origin redirects",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N",
      "metrics": {
       "baseScore": 5.9,
       "exploitabilityScore": 0.7,
       "impactScore": 5.2
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "1.26.17"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-43804",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-43804",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb",
      "https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d",
      "https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f",
      "https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/"
     ],
     "description": "urllib3 is a user-friendly HTTP client library for Python. urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly. This issue has been patched in urllib3 version 1.26.17 or 2.0.5.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
       "metrics": {
        "baseScore": 8.1,
        "exploitabilityScore": 2.8,
        "impactScore": 5.2
       },
       "vendorMetadata": {}
      },
      {
       "source": "security-advisories@github.com",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N",
       "metrics": {
        "baseScore": 5.9,
        "exploitabilityScore": 0.7,
        "impactScore": 5.2
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "urllib3",
       "version": "1.26.5"
      }
     },
     "found": {
      "versionConstraint": "<1.26.17 (python)",
      "vulnerabilityID": "GHSA-v845-jxx5-vc9f"
     }
    }
   ],
   "artifact": {
    "id": "66f56bdc0c84c79d",
    "name": "urllib3",
    "version": "1.26.5",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "MIT"
    ],
    "cpes": [],
    "purl": "pkg:pypi/urllib3@1.26.5",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-g4mx-q9vg-27p4",
    "dataSource": "https://github.com/advisories/GHSA-g4mx-q9vg-27p4",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-g4mx-q9vg-27p4"
    ],
    "description": "urllib3's request body not stripped after redirect from 303 status changes request method to GET",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
      "metrics": {
       "baseScore": 4.2,
       "exploitabilityScore": 0.5,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "1.26.18"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-45803",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-45803",
     "namespace": "nvd:cpe",
     "severity": "Medium",
     "urls": [
      "https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9",
      "https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/",
      "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/",
      "https://www.rfc-editor.org/rfc/rfc9110.html#name-get"
     ],
     "description": "urllib3 is a user-friendly HTTP client library for Python. urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 301, 302, or 303 after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although this behavior is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers. Because the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable. Both of the following conditions must be true to be affected by this vulnerability: 1. Using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON) and 2. The origin service is compromised and starts redirecting using 301, 302, or 303 to a malicious peer or the redirected-to service becomes compromised. This issue has been addressed in versions 1.26.18 and 2.0.7 and users are advised to update to resolve this issue. Users unable to update should disable redirects for services that aren't expecting to respond with redirects with `redirects=False` and disable automatic redirects with `redirects=False` and handle 301, 302, and 303 redirects manually by stripping the HTTP request body.\n",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
       "metrics": {
        "baseScore": 4.2,
        "exploitabilityScore": 0.5,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      },
      {
       "source": "security-advisories@github.com",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
       "metrics": {
        "baseScore": 4.2,
        "exploitabilityScore": 0.5,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "urllib3",
       "version": "1.26.5"
      }
     },
     "found": {
      "versionConstraint": ">=0,<1.26.18 (python)",
      "vulnerabilityID": "GHSA-g4mx-q9vg-27p4"
     }
    }
   ],
   "artifact": {
    "id": "66f56bdc0c84c79d",
    "name": "urllib3",
    "version": "1.26.5",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "MIT"
    ],
    "cpes": [],
    "purl": "pkg:pypi/urllib3@1.26.5",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-xg9f-g7g7-2323",
    "dataSource": "https://github.com/advisories/GHSA-xg9f-g7g7-2323",
    "namespace": "github:language:python",
    "severity": "High",
    "urls": [
     "https://github.com/advisories/GHSA-xg9f-g7g7-2323"
    ],
    "description": "High resource usage when parsing multipart form data with many fields",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "metrics": {
       "baseScore": 7.5,
       "exploitabilityScore": 3.9,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "High",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "2.2.3"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-25577",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-25577",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://github.com/pallets/werkzeug/commit/517cac5a804e8c4dc4ed038bb20dacd038e7a9f1",
      "https://github.com/pallets/werkzeug/releases/tag/2.2.3",
      "https://github.com/pallets/werkzeug/security/advisories/GHSA-xg9f-g7g7-2323",
      "https://security.netapp.com/advisory/ntap-20230818-0003/",
      "https://www.debian.org/security/2023/dsa-5470"
     ],
     "description": "Werkzeug is a comprehensive WSGI web application library. Prior to version 2.2.3, Werkzeug's multipart form data parser will parse an unlimited number of parts, including file parts. Parts can be a small amount of bytes, but each requires CPU time to parse and may use more memory as Python data. If a request can be made to an endpoint that accesses `request.data`, `request.form`, `request.files`, or `request.get_data(parse_form_data=False)`, it can cause unexpectedly high resource usage. This allows an attacker to cause a denial of service by sending crafted multipart data to an endpoint that will parse it. The amount of CPU time required can block worker processes from handling legitimate requests. The amount of RAM required can trigger an out of memory kill of the process. Unlimited file parts can use up memory and file handles. If many concurrent requests are sent continuously, this can exhaust or kill all available workers. Version 2.2.3 contains a patch for this issue.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      },
      {
       "source": "security-advisories@github.com",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "werkzeug",
       "version": "2.0.2"
      }
     },
     "found": {
      "versionConstraint": "<2.2.3 (python)",
      "vulnerabilityID": "GHSA-xg9f-g7g7-2323"
     }
    }
   ],
   "artifact": {
    "id": "73aed898988a7c1b",
    "name": "werkzeug",
    "version": "2.0.2",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "BSD-3-Clause"
    ],
    "cpes": [],
    "purl": "pkg:pypi/werkzeug@2.0.2",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-hrfv-mqp8-q5rw",
    "dataSource": "https://github.com/advisories/GHSA-hrfv-mqp8-q5rw",
    "namespace": "github:language:python",
    "severity": "Medium",
    "urls": [
     "https://github.com/advisories/GHSA-hrfv-mqp8-q5rw"
    ],
    "description": "Werkzeug DoS: High resource usage when parsing multipart/form-data containing a large part with CR/LF character at the beginning",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
      "metrics": {
       "baseScore": 5.7,
       "exploitabilityScore": 2.1,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "Medium",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "2.3.8"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-46136",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-46136",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://github.com/pallets/werkzeug/commit/f3c803b3ade485a45f12b6d6617595350c0f03e2",
      "https://github.com/pallets/werkzeug/security/advisories/GHSA-hrfv-mqp8-q5rw",
      "https://security.netapp.com/advisory/ntap-20231124-0008/"
     ],
     "description": "Werkzeug is a comprehensive WSGI web application library. If an upload of a file that starts with CR or LF and then is followed by megabytes of data without these characters: all of these bytes are appended chunk by chunk into internal bytearray and lookup for boundary is performed on growing buffer. This allows an attacker to cause a denial of service by sending crafted multipart data to an endpoint that will parse it. The amount of CPU time required can block worker processes from handling legitimate requests. This vulnerability has been patched in version 3.0.1.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      },
      {
       "source": "security-advisories@github.com",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
       "metrics": {
        "baseScore": 8,
        "exploitabilityScore": 2.1,
        "impactScore": 5.9
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "werkzeug",
       "version": "2.0.2"
      }
     },
     "found": {
      "versionConstraint": "<2.3.8 (python)",
      "vulnerabilityID": "GHSA-hrfv-mqp8-q5rw"
     }
    }
   ],
   "artifact": {
    "id": "73aed898988a7c1b",
    "name": "werkzeug",
    "version": "2.0.2",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "BSD-3-Clause"
    ],
    "cpes": [],
    "purl": "pkg:pypi/werkzeug@2.0.2",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-px8h-6qxv-m22q",
    "dataSource": "https://github.com/advisories/GHSA-px8h-6qxv-m22q",
    "namespace": "github:language:python",
    "severity": "Low",
    "urls": [
     "https://github.com/advisories/GHSA-px8h-6qxv-m22q"
    ],
    "description": "Incorrect parsing of nameless cookies leads to __Host- cookies bypass",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:A/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:N",
      "metrics": {
       "baseScore": 2.6,
       "exploitabilityScore": 1.2,
       "impactScore": 1.4
      },
      "vendorMetadata": {
       "base_severity": "Low",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "2.2.3"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2023-23934",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2023-23934",
     "namespace": "nvd:cpe",
     "severity": "Low",
     "urls": [
      "https://github.com/pallets/werkzeug/commit/cf275f42acad1b5950c50ffe8ef58fe62cdce028",
      "https://github.com/pallets/werkzeug/releases/tag/2.2.3",
      "https://github.com/pallets/werkzeug/security/advisories/GHSA-px8h-6qxv-m22q",
      "https://security.netapp.com/advisory/ntap-20230818-0003/",
      "https://www.debian.org/security/2023/dsa-5470"
     ],
     "description": "Werkzeug is a comprehensive WSGI web application library. Browsers may allow \"nameless\" cookies that look like `=value` instead of `key=value`. A vulnerable browser may allow a compromised application on an adjacent subdomain to exploit this to set a cookie like `=__Host-test=bad` for another subdomain. Werkzeug prior to 2.2.3 will parse the cookie `=__Host-test=bad` as __Host-test=bad`. If a Werkzeug application is running next to a vulnerable or malicious subdomain which sets such a cookie using a vulnerable browser, the Werkzeug application will see the bad cookie value but the valid cookie key. The issue is fixed in Werkzeug 2.2.3.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:A/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N",
       "metrics": {
        "baseScore": 3.5,
        "exploitabilityScore": 2.1,
        "impactScore": 1.4
       },
       "vendorMetadata": {}
      },
      {
       "source": "security-advisories@github.com",
       "type": "Secondary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:A/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:N",
       "metrics": {
        "baseScore": 2.6,
        "exploitabilityScore": 1.2,
        "impactScore": 1.4
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "werkzeug",
       "version": "2.0.2"
      }
     },
     "found": {
      "versionConstraint": "<2.2.3 (python)",
      "vulnerabilityID": "GHSA-px8h-6qxv-m22q"
     }
    }
   ],
   "artifact": {
    "id": "73aed898988a7c1b",
    "name": "werkzeug",
    "version": "2.0.2",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "BSD-3-Clause"
    ],
    "cpes": [],
    "purl": "pkg:pypi/werkzeug@2.0.2",
    "upstreams": []
   }
  },
  {
   "vulnerability": {
    "id": "GHSA-qwmp-2cf2-g9g6",
    "dataSource": "https://github.com/advisories/GHSA-qwmp-2cf2-g9g6",
    "namespace": "github:language:python",
    "severity": "High",
    "urls": [
     "https://github.com/advisories/GHSA-qwmp-2cf2-g9g6"
    ],
    "description": "pypa/wheel vulnerable to Regular Expression denial of service (ReDoS)",
    "cvss": [
     {
      "version": "3.1",
      "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
      "metrics": {
       "baseScore": 7.5,
       "exploitabilityScore": 3.9,
       "impactScore": 3.6
      },
      "vendorMetadata": {
       "base_severity": "High",
       "status": "N/A"
      }
     }
    ],
    "fix": {
     "versions": [
      "0.38.1"
     ],
     "state": "fixed"
    },
    "advisories": []
   },
   "relatedVulnerabilities": [
    {
     "id": "CVE-2022-40898",
     "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2022-40898",
     "namespace": "nvd:cpe",
     "severity": "High",
     "urls": [
      "https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18",
      "https://pypi.org/project/wheel/",
      "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/"
     ],
     "description": "An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli.",
     "cvss": [
      {
       "source": "nvd@nist.gov",
       "type": "Primary",
       "version": "3.1",
       "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
       "metrics": {
        "baseScore": 7.5,
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
       },
       "vendorMetadata": {}
      }
     ]
    }
   ],
   "matchDetails": [
    {
     "type": "exact-direct-match",
     "matcher": "python-matcher",
     "searchedBy": {
      "language": "python",
      "namespace": "github:language:python",
      "package": {
       "name": "wheel",
       "version": "0.37.1"
      }
     },
     "found": {
      "versionConstraint": "<=0.37.1 (python)",
      "vulnerabilityID": "GHSA-qwmp-2cf2-g9g6"
     }
    }
   ],
   "artifact": {
    "id": "e936f21cc01c80c4",
    "name": "wheel",
    "version": "0.37.1",
    "type": "python",
    "locations": [],
    "language": "python",
    "licenses": [
     "MIT"
    ],
    "cpes": [],
    "purl": "pkg:pypi/wheel@0.37.1",
    "upstreams": []
   }
  }
 ],
 "source": {
  "type": "image",
  "target": {
   "userInput": "",
   "imageID": "",
   "manifestDigest": "",
   "mediaType": "",
   "tags": [],
   "imageSize": 0,
   "layers": null,
   "manifest": null,
   "config": null,
   "repoDigests": [],
   "architecture": "",
   "os": ""
  }
 },
 "distro": {
  "name": "",
  "version": "",
  "idLike": null
 },
 "descriptor": {
  "name": "grype",
  "version": "0.74.0",
  "configuration": {
   "output": [
    "json"
   ],
   "file": "",
   "distro": "",
   "add-cpes-if-none": false,
   "output-template-file": "",
   "check-for-app-update": true,
   "only-fixed": false,
   "only-notfixed": false,
   "ignore-wontfix": "",
   "platform": "",
   "search": {
    "scope": "squashed",
    "unindexed-archives": false,
    "indexed-archives": true
   },
   "ignore": null,
   "exclude": [],
   "db": {
    "cache-dir": "/Users/katushka/Library/Caches/grype/db",
    "update-url": "https://toolbox-data.anchore.io/grype/databases/listing.json",
    "ca-cert": "",
    "auto-update": true,
    "validate-by-hash-on-start": false,
    "validate-age": true,
    "max-allowed-built-age": 432000000000000
   },
   "externalSources": {
    "enable": false,
    "maven": {
     "searchUpstreamBySha1": true,
     "baseUrl": "https://search.maven.org/solrsearch/select"
    }
   },
   "match": {
    "java": {
     "using-cpes": false
    },
    "dotnet": {
     "using-cpes": false
    },
    "golang": {
     "using-cpes": false,
     "always-use-cpe-for-stdlib": true
    },
    "javascript": {
     "using-cpes": false
    },
    "python": {
     "using-cpes": false
    },
    "ruby": {
     "using-cpes": false
    },
    "rust": {
     "using-cpes": false
    },
    "stock": {
     "using-cpes": true
    }
   },
   "fail-on-severity": "",
   "registry": {
    "insecure-skip-tls-verify": false,
    "insecure-use-http": false,
    "auth": null,
    "ca-cert": ""
   },
   "show-suppressed": false,
   "by-cve": false,
   "name": "",
   "default-image-pull-source": "",
   "vex-documents": [],
   "vex-add": []
  },
  "db": {
   "built": "2024-04-20T01:25:41Z",
   "schemaVersion": 5,
   "location": "/Users/katushka/Library/Caches/grype/db/5",
   "checksum": "sha256:16b261c20c43828088d3530bdb10577ad87b9d33cfbfcaf051c3af61ba7e53ca",
   "error": null
  },
  "timestamp": "2024-04-20T21:50:46.524967+02:00"
 }
}
